//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类app_service_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("app_service_info")]
	[Serializable]
	public partial class app_service_info : Entity 
	{
		#region Model
		private int _id;
		private string _sp_id;
		private string _app_cpid;
		private string _pid;
		private string _pidremark;
		private string _pidremark2;
		private string _app_id;
		private string _itemId;
		private int? _price;
		private DateTime? _coop_date;
		private int _coop_status;
		private string _itemSafeLevel;
		private string _itemMethod;
		private string _itemExt;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 接口cp
		/// </summary>
		public string app_cpid
		{
			get{ return _app_cpid; }
			set
			{
				this.OnPropertyValueChange(_.app_cpid,_app_cpid,value);
				this._app_cpid=value;
			}
		}
		/// <summary>
		/// 接口pid
		/// </summary>
		public string pid
		{
			get{ return _pid; }
			set
			{
				this.OnPropertyValueChange(_.pid,_pid,value);
				this._pid=value;
			}
		}
		/// <summary>
		/// 价格
		/// </summary>
		public string pidremark
		{
			get{ return _pidremark; }
			set
			{
				this.OnPropertyValueChange(_.pidremark,_pidremark,value);
				this._pidremark=value;
			}
		}
		/// <summary>
		/// 道具代码
		/// </summary>
		public string pidremark2
		{
			get{ return _pidremark2; }
			set
			{
				this.OnPropertyValueChange(_.pidremark2,_pidremark2,value);
				this._pidremark2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_id
		{
			get{ return _app_id; }
			set
			{
				this.OnPropertyValueChange(_.app_id,_app_id,value);
				this._app_id=value;
			}
		}
		/// <summary>
		/// 指令编号
		/// </summary>
		public string itemId
		{
			get{ return _itemId; }
			set
			{
				this.OnPropertyValueChange(_.itemId,_itemId,value);
				this._itemId=value;
			}
		}
		/// <summary>
		/// 资费
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 合作时间
		/// </summary>
		public DateTime? coop_date
		{
			get{ return _coop_date; }
			set
			{
				this.OnPropertyValueChange(_.coop_date,_coop_date,value);
				this._coop_date=value;
			}
		}
		/// <summary>
		/// _0 开通 1关闭
		/// </summary>
		public int coop_status
		{
			get{ return _coop_status; }
			set
			{
				this.OnPropertyValueChange(_.coop_status,_coop_status,value);
				this._coop_status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string itemSafeLevel
		{
			get{ return _itemSafeLevel; }
			set
			{
				this.OnPropertyValueChange(_.itemSafeLevel,_itemSafeLevel,value);
				this._itemSafeLevel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string itemMethod
		{
			get{ return _itemMethod; }
			set
			{
				this.OnPropertyValueChange(_.itemMethod,_itemMethod,value);
				this._itemMethod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string itemExt
		{
			get{ return _itemExt; }
			set
			{
				this.OnPropertyValueChange(_.itemExt,_itemExt,value);
				this._itemExt=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.sp_id,
				_.app_cpid,
				_.pid,
				_.pidremark,
				_.pidremark2,
				_.app_id,
				_.itemId,
				_.price,
				_.coop_date,
				_.coop_status,
				_.itemSafeLevel,
				_.itemMethod,
				_.itemExt};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._sp_id,
				this._app_cpid,
				this._pid,
				this._pidremark,
				this._pidremark2,
				this._app_id,
				this._itemId,
				this._price,
				this._coop_date,
				this._coop_status,
				this._itemSafeLevel,
				this._itemMethod,
				this._itemExt};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","app_service_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","app_service_info","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","app_service_info","sp_id");
			/// <summary>
			/// 接口cp
			/// </summary>
			public readonly static Field app_cpid = new Field("app_cpid","app_service_info","接口cp");
			/// <summary>
			/// 接口pid
			/// </summary>
			public readonly static Field pid = new Field("pid","app_service_info","接口pid");
			/// <summary>
			/// 价格
			/// </summary>
			public readonly static Field pidremark = new Field("pidremark","app_service_info","价格");
			/// <summary>
			/// 道具代码
			/// </summary>
			public readonly static Field pidremark2 = new Field("pidremark2","app_service_info","道具代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_id = new Field("app_id","app_service_info","app_id");
			/// <summary>
			/// 指令编号
			/// </summary>
			public readonly static Field itemId = new Field("itemId","app_service_info","指令编号");
			/// <summary>
			/// 资费
			/// </summary>
			public readonly static Field price = new Field("price","app_service_info","资费");
			/// <summary>
			/// 合作时间
			/// </summary>
			public readonly static Field coop_date = new Field("coop_date","app_service_info","合作时间");
			/// <summary>
			/// _0 开通 1关闭
			/// </summary>
			public readonly static Field coop_status = new Field("coop_status","app_service_info","_0 开通 1关闭");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field itemSafeLevel = new Field("itemSafeLevel","app_service_info","itemSafeLevel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field itemMethod = new Field("itemMethod","app_service_info","itemMethod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field itemExt = new Field("itemExt","app_service_info","itemExt");
		}
		#endregion


	}
}

