//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类app_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("app_info")]
	[Serializable]
	public partial class app_info : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _appname;
		private string _key;
		private string _cp_id;
		private string _sp_id;
		private string _sid;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appname
		{
			get{ return _appname; }
			set
			{
				this.OnPropertyValueChange(_.appname,_appname,value);
				this._appname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string key
		{
			get{ return _key; }
			set
			{
				this.OnPropertyValueChange(_.key,_key,value);
				this._key=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sid
		{
			get{ return _sid; }
			set
			{
				this.OnPropertyValueChange(_.sid,_sid,value);
				this._sid=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.appname,
				_.key,
				_.cp_id,
				_.sp_id,
				_.sid};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._appname,
				this._key,
				this._cp_id,
				this._sp_id,
				this._sid};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","app_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","app_info","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","app_info","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appname = new Field("appname","app_info","appname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field key = new Field("key","app_info","key");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","app_info","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","app_info","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sid = new Field("sid","app_info","sid");
		}
		#endregion


	}
}

