//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类app_pay_record 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("app_pay_record")]
	[Serializable]
	public partial class app_pay_record : Entity 
	{
		#region Model
		private int _id;
		private string _msgType;
		private string _appid;
		private string _channelId;
		private string _imsi;
		private string _imei;
		private int? _price;
		private string _cpparam;
		private string _clientip;
		private string _nyurl;
		private string _subtime;
		private string _result;
		private string _deltime;
		private int? _report_stat;
		private int? _report_times;
		private string _seqId;
		private string _req_message;
		private string _code_message;
		private string _phoneNum;
		private string _province_id;
		private string _area_code;
		private string _src_appid;
		private int? _src_price;
		private string _src_channelId;
		private string _closd_stat;
		private string _cp_id;
		private string _src_cp_id;
		private string _sp_id;
		private string _src_sp_id;
		private string _result_message;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 请求类型
		/// </summary>
		public string msgType
		{
			get{ return _msgType; }
			set
			{
				this.OnPropertyValueChange(_.msgType,_msgType,value);
				this._msgType=value;
			}
		}
		/// <summary>
		/// app应用
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 渠道号
		/// </summary>
		public string channelId
		{
			get{ return _channelId; }
			set
			{
				this.OnPropertyValueChange(_.channelId,_channelId,value);
				this._channelId=value;
			}
		}
		/// <summary>
		/// 手机串号
		/// </summary>
		public string imsi
		{
			get{ return _imsi; }
			set
			{
				this.OnPropertyValueChange(_.imsi,_imsi,value);
				this._imsi=value;
			}
		}
		/// <summary>
		/// 设备识别码
		/// </summary>
		public string imei
		{
			get{ return _imei; }
			set
			{
				this.OnPropertyValueChange(_.imei,_imei,value);
				this._imei=value;
			}
		}
		/// <summary>
		/// 价格
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 透传字段
		/// </summary>
		public string cpparam
		{
			get{ return _cpparam; }
			set
			{
				this.OnPropertyValueChange(_.cpparam,_cpparam,value);
				this._cpparam=value;
			}
		}
		/// <summary>
		/// 客户端ip
		/// </summary>
		public string clientip
		{
			get{ return _clientip; }
			set
			{
				this.OnPropertyValueChange(_.clientip,_clientip,value);
				this._clientip=value;
			}
		}
		/// <summary>
		/// 同步地址
		/// </summary>
		public string nyurl
		{
			get{ return _nyurl; }
			set
			{
				this.OnPropertyValueChange(_.nyurl,_nyurl,value);
				this._nyurl=value;
			}
		}
		/// <summary>
		/// 请求时间
		/// </summary>
		public string subtime
		{
			get{ return _subtime; }
			set
			{
				this.OnPropertyValueChange(_.subtime,_subtime,value);
				this._subtime=value;
			}
		}
		/// <summary>
		/// _0表示计费成功，其它为失败
		/// </summary>
		public string result
		{
			get{ return _result; }
			set
			{
				this.OnPropertyValueChange(_.result,_result,value);
				this._result=value;
			}
		}
		/// <summary>
		/// 扣费时间
		/// </summary>
		public string deltime
		{
			get{ return _deltime; }
			set
			{
				this.OnPropertyValueChange(_.deltime,_deltime,value);
				this._deltime=value;
			}
		}
		/// <summary>
		/// _0 未发送 1已发送
		/// </summary>
		public int? report_stat
		{
			get{ return _report_stat; }
			set
			{
				this.OnPropertyValueChange(_.report_stat,_report_stat,value);
				this._report_stat=value;
			}
		}
		/// <summary>
		/// 发送给合作方次数
		/// </summary>
		public int? report_times
		{
			get{ return _report_times; }
			set
			{
				this.OnPropertyValueChange(_.report_times,_report_times,value);
				this._report_times=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string seqId
		{
			get{ return _seqId; }
			set
			{
				this.OnPropertyValueChange(_.seqId,_seqId,value);
				this._seqId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string req_message
		{
			get{ return _req_message; }
			set
			{
				this.OnPropertyValueChange(_.req_message,_req_message,value);
				this._req_message=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string code_message
		{
			get{ return _code_message; }
			set
			{
				this.OnPropertyValueChange(_.code_message,_code_message,value);
				this._code_message=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string phoneNum
		{
			get{ return _phoneNum; }
			set
			{
				this.OnPropertyValueChange(_.phoneNum,_phoneNum,value);
				this._phoneNum=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string area_code
		{
			get{ return _area_code; }
			set
			{
				this.OnPropertyValueChange(_.area_code,_area_code,value);
				this._area_code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string src_appid
		{
			get{ return _src_appid; }
			set
			{
				this.OnPropertyValueChange(_.src_appid,_src_appid,value);
				this._src_appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? src_price
		{
			get{ return _src_price; }
			set
			{
				this.OnPropertyValueChange(_.src_price,_src_price,value);
				this._src_price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string src_channelId
		{
			get{ return _src_channelId; }
			set
			{
				this.OnPropertyValueChange(_.src_channelId,_src_channelId,value);
				this._src_channelId=value;
			}
		}
		/// <summary>
		/// 核减状态
		/// </summary>
		public string closd_stat
		{
			get{ return _closd_stat; }
			set
			{
				this.OnPropertyValueChange(_.closd_stat,_closd_stat,value);
				this._closd_stat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string src_cp_id
		{
			get{ return _src_cp_id; }
			set
			{
				this.OnPropertyValueChange(_.src_cp_id,_src_cp_id,value);
				this._src_cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string src_sp_id
		{
			get{ return _src_sp_id; }
			set
			{
				this.OnPropertyValueChange(_.src_sp_id,_src_sp_id,value);
				this._src_sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string result_message
		{
			get{ return _result_message; }
			set
			{
				this.OnPropertyValueChange(_.result_message,_result_message,value);
				this._result_message=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.msgType,
				_.appid,
				_.channelId,
				_.imsi,
				_.imei,
				_.price,
				_.cpparam,
				_.clientip,
				_.nyurl,
				_.subtime,
				_.result,
				_.deltime,
				_.report_stat,
				_.report_times,
				_.seqId,
				_.req_message,
				_.code_message,
				_.phoneNum,
				_.province_id,
				_.area_code,
				_.src_appid,
				_.src_price,
				_.src_channelId,
				_.closd_stat,
				_.cp_id,
				_.src_cp_id,
				_.sp_id,
				_.src_sp_id,
				_.result_message};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._msgType,
				this._appid,
				this._channelId,
				this._imsi,
				this._imei,
				this._price,
				this._cpparam,
				this._clientip,
				this._nyurl,
				this._subtime,
				this._result,
				this._deltime,
				this._report_stat,
				this._report_times,
				this._seqId,
				this._req_message,
				this._code_message,
				this._phoneNum,
				this._province_id,
				this._area_code,
				this._src_appid,
				this._src_price,
				this._src_channelId,
				this._closd_stat,
				this._cp_id,
				this._src_cp_id,
				this._sp_id,
				this._src_sp_id,
				this._result_message};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","app_pay_record");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","app_pay_record","id");
			/// <summary>
			/// 请求类型
			/// </summary>
			public readonly static Field msgType = new Field("msgType","app_pay_record","请求类型");
			/// <summary>
			/// app应用
			/// </summary>
			public readonly static Field appid = new Field("appid","app_pay_record","app应用");
			/// <summary>
			/// 渠道号
			/// </summary>
			public readonly static Field channelId = new Field("channelId","app_pay_record","渠道号");
			/// <summary>
			/// 手机串号
			/// </summary>
			public readonly static Field imsi = new Field("imsi","app_pay_record","手机串号");
			/// <summary>
			/// 设备识别码
			/// </summary>
			public readonly static Field imei = new Field("imei","app_pay_record","设备识别码");
			/// <summary>
			/// 价格
			/// </summary>
			public readonly static Field price = new Field("price","app_pay_record","价格");
			/// <summary>
			/// 透传字段
			/// </summary>
			public readonly static Field cpparam = new Field("cpparam","app_pay_record","透传字段");
			/// <summary>
			/// 客户端ip
			/// </summary>
			public readonly static Field clientip = new Field("clientip","app_pay_record","客户端ip");
			/// <summary>
			/// 同步地址
			/// </summary>
			public readonly static Field nyurl = new Field("nyurl","app_pay_record","同步地址");
			/// <summary>
			/// 请求时间
			/// </summary>
			public readonly static Field subtime = new Field("subtime","app_pay_record","请求时间");
			/// <summary>
			/// _0表示计费成功，其它为失败
			/// </summary>
			public readonly static Field result = new Field("result","app_pay_record","_0表示计费成功，其它为失败");
			/// <summary>
			/// 扣费时间
			/// </summary>
			public readonly static Field deltime = new Field("deltime","app_pay_record","扣费时间");
			/// <summary>
			/// _0 未发送 1已发送
			/// </summary>
			public readonly static Field report_stat = new Field("report_stat","app_pay_record","_0 未发送 1已发送");
			/// <summary>
			/// 发送给合作方次数
			/// </summary>
			public readonly static Field report_times = new Field("report_times","app_pay_record","发送给合作方次数");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field seqId = new Field("seqId","app_pay_record","seqId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field req_message = new Field("req_message","app_pay_record","req_message");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field code_message = new Field("code_message","app_pay_record","code_message");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field phoneNum = new Field("phoneNum","app_pay_record","phoneNum");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","app_pay_record","province_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field area_code = new Field("area_code","app_pay_record","area_code");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_appid = new Field("src_appid","app_pay_record","src_appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_price = new Field("src_price","app_pay_record","src_price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_channelId = new Field("src_channelId","app_pay_record","src_channelId");
			/// <summary>
			/// 核减状态
			/// </summary>
			public readonly static Field closd_stat = new Field("closd_stat","app_pay_record","核减状态");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","app_pay_record","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_cp_id = new Field("src_cp_id","app_pay_record","src_cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","app_pay_record","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_sp_id = new Field("src_sp_id","app_pay_record","src_sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field result_message = new Field("result_message","app_pay_record","result_message");
		}
		#endregion


	}
}

