//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类channel_month_cp_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("channel_month_cp_info")]
	[Serializable]
	public partial class channel_month_cp_info : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _cp_cn;
		private string _cp_en;
		private string _parent_cp;
		private string _src_cp_id;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 合作方代码
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 中文名
		/// </summary>
		public string cp_cn
		{
			get{ return _cp_cn; }
			set
			{
				this.OnPropertyValueChange(_.cp_cn,_cp_cn,value);
				this._cp_cn=value;
			}
		}
		/// <summary>
		/// 英语名、拼音
		/// </summary>
		public string cp_en
		{
			get{ return _cp_en; }
			set
			{
				this.OnPropertyValueChange(_.cp_en,_cp_en,value);
				this._cp_en=value;
			}
		}
		/// <summary>
		/// 归属父级合作方
		/// </summary>
		public string parent_cp
		{
			get{ return _parent_cp; }
			set
			{
				this.OnPropertyValueChange(_.parent_cp,_parent_cp,value);
				this._parent_cp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string src_cp_id
		{
			get{ return _src_cp_id; }
			set
			{
				this.OnPropertyValueChange(_.src_cp_id,_src_cp_id,value);
				this._src_cp_id=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.cp_cn,
				_.cp_en,
				_.parent_cp,
				_.src_cp_id};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._cp_cn,
				this._cp_en,
				this._parent_cp,
				this._src_cp_id};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","channel_month_cp_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","channel_month_cp_info","id");
			/// <summary>
			/// 合作方代码
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","channel_month_cp_info","合作方代码");
			/// <summary>
			/// 中文名
			/// </summary>
			public readonly static Field cp_cn = new Field("cp_cn","channel_month_cp_info","中文名");
			/// <summary>
			/// 英语名、拼音
			/// </summary>
			public readonly static Field cp_en = new Field("cp_en","channel_month_cp_info","英语名、拼音");
			/// <summary>
			/// 归属父级合作方
			/// </summary>
			public readonly static Field parent_cp = new Field("parent_cp","channel_month_cp_info","归属父级合作方");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field src_cp_id = new Field("src_cp_id","channel_month_cp_info","src_cp_id");
		}
		#endregion


	}
}

