//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类channel_month_cp_province 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("channel_month_cp_province")]
	[Serializable]
	public partial class channel_month_cp_province : Entity 
	{
		#region Model
		private long _id;
		private string _cpid;
		private string _limit_miscid;
		private int? _close_stat;
		private string _spid;
		private DateTime? _mod_time;
		private string _mod_user;
		/// <summary>
		/// 
		/// </summary>
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 合作方
		/// </summary>
		public string cpid
		{
			get{ return _cpid; }
			set
			{
				this.OnPropertyValueChange(_.cpid,_cpid,value);
				this._cpid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string limit_miscid
		{
			get{ return _limit_miscid; }
			set
			{
				this.OnPropertyValueChange(_.limit_miscid,_limit_miscid,value);
				this._limit_miscid=value;
			}
		}
		/// <summary>
		/// _0不关闭省份 1关闭省份
		/// </summary>
		public int? close_stat
		{
			get{ return _close_stat; }
			set
			{
				this.OnPropertyValueChange(_.close_stat,_close_stat,value);
				this._close_stat=value;
			}
		}
		/// <summary>
		/// 公司
		/// </summary>
		public string spid
		{
			get{ return _spid; }
			set
			{
				this.OnPropertyValueChange(_.spid,_spid,value);
				this._spid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? mod_time
		{
			get{ return _mod_time; }
			set
			{
				this.OnPropertyValueChange(_.mod_time,_mod_time,value);
				this._mod_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string mod_user
		{
			get{ return _mod_user; }
			set
			{
				this.OnPropertyValueChange(_.mod_user,_mod_user,value);
				this._mod_user=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cpid,
				_.limit_miscid,
				_.close_stat,
				_.spid,
				_.mod_time,
				_.mod_user};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cpid,
				this._limit_miscid,
				this._close_stat,
				this._spid,
				this._mod_time,
				this._mod_user};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","channel_month_cp_province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","channel_month_cp_province","id");
			/// <summary>
			/// 合作方
			/// </summary>
			public readonly static Field cpid = new Field("cpid","channel_month_cp_province","合作方");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field limit_miscid = new Field("limit_miscid","channel_month_cp_province","limit_miscid");
			/// <summary>
			/// _0不关闭省份 1关闭省份
			/// </summary>
			public readonly static Field close_stat = new Field("close_stat","channel_month_cp_province","_0不关闭省份 1关闭省份");
			/// <summary>
			/// 公司
			/// </summary>
			public readonly static Field spid = new Field("spid","channel_month_cp_province","公司");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mod_time = new Field("mod_time","channel_month_cp_province","mod_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mod_user = new Field("mod_user","channel_month_cp_province","mod_user");
		}
		#endregion


	}
}

