//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类channel_month_appinfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("channel_month_appinfo")]
	[Serializable]
	public partial class channel_month_appinfo : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _appname;
		private string _appkey;
		private string _cp_id;
		private string _sp_id;
		private string _sid;
		private string _price;
		private string _paycode;
		private string _sub_appname;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appname
		{
			get{ return _appname; }
			set
			{
				this.OnPropertyValueChange(_.appname,_appname,value);
				this._appname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appkey
		{
			get{ return _appkey; }
			set
			{
				this.OnPropertyValueChange(_.appkey,_appkey,value);
				this._appkey=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sid
		{
			get{ return _sid; }
			set
			{
				this.OnPropertyValueChange(_.sid,_sid,value);
				this._sid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sub_appname
		{
			get{ return _sub_appname; }
			set
			{
				this.OnPropertyValueChange(_.sub_appname,_sub_appname,value);
				this._sub_appname=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.appname,
				_.appkey,
				_.cp_id,
				_.sp_id,
				_.sid,
				_.price,
				_.paycode,
				_.sub_appname};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._appname,
				this._appkey,
				this._cp_id,
				this._sp_id,
				this._sid,
				this._price,
				this._paycode,
				this._sub_appname};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","channel_month_appinfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","channel_month_appinfo","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","channel_month_appinfo","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appname = new Field("appname","channel_month_appinfo","appname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appkey = new Field("appkey","channel_month_appinfo","appkey");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","channel_month_appinfo","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","channel_month_appinfo","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sid = new Field("sid","channel_month_appinfo","sid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","channel_month_appinfo","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","channel_month_appinfo","paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sub_appname = new Field("sub_appname","channel_month_appinfo","sub_appname");
		}
		#endregion


	}
}

