//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类channelid 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("channelid")]
	[Serializable]
	public partial class channelid : Entity 
	{
		#region Model
		private int _id;
		private string _sp_id;
		private string _cp_id;
		private string _channelid;
		private int? _status;
		private string _opentime;
		private string _closetime;
		private string _openuser;
		private string _closeuser;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channelId
		{
			get{ return _channelid; }
			set
			{
				this.OnPropertyValueChange(_.channelid,_channelid,value);
				this._channelid=value;
			}
		}
		/// <summary>
		/// _0关闭  1开通
		/// </summary>
		public int? status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 开通时间
		/// </summary>
		public string opentime
		{
			get{ return _opentime; }
			set
			{
				this.OnPropertyValueChange(_.opentime,_opentime,value);
				this._opentime=value;
			}
		}
		/// <summary>
		/// 关闭时间
		/// </summary>
		public string closetime
		{
			get{ return _closetime; }
			set
			{
				this.OnPropertyValueChange(_.closetime,_closetime,value);
				this._closetime=value;
			}
		}
		/// <summary>
		/// 开通人
		/// </summary>
		public string openuser
		{
			get{ return _openuser; }
			set
			{
				this.OnPropertyValueChange(_.openuser,_openuser,value);
				this._openuser=value;
			}
		}
		/// <summary>
		/// 关闭人
		/// </summary>
		public string closeuser
		{
			get{ return _closeuser; }
			set
			{
				this.OnPropertyValueChange(_.closeuser,_closeuser,value);
				this._closeuser=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.sp_id,
				_.cp_id,
				_.channelid,
				_.status,
				_.opentime,
				_.closetime,
				_.openuser,
				_.closeuser};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._sp_id,
				this._cp_id,
				this._channelid,
				this._status,
				this._opentime,
				this._closetime,
				this._openuser,
				this._closeuser};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","channelid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","channelid","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","channelid","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","channelid","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channelid = new Field("channelid","channelid","channelid");
			/// <summary>
			/// _0关闭  1开通
			/// </summary>
			public readonly static Field status = new Field("status","channelid","_0关闭  1开通");
			/// <summary>
			/// 开通时间
			/// </summary>
			public readonly static Field opentime = new Field("opentime","channelid","开通时间");
			/// <summary>
			/// 关闭时间
			/// </summary>
			public readonly static Field closetime = new Field("closetime","channelid","关闭时间");
			/// <summary>
			/// 开通人
			/// </summary>
			public readonly static Field openuser = new Field("openuser","channelid","开通人");
			/// <summary>
			/// 关闭人
			/// </summary>
			public readonly static Field closeuser = new Field("closeuser","channelid","关闭人");
		}
		#endregion


	}
}

