//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类cp_cooperate 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("cp_cooperate")]
	[Serializable]
	public partial class cp_cooperate : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _sp_id;
		private int _coop_status;
		private DateTime? _coop_date;
		private object _turn_on_time;
		private object _turn_off_time;
		private string _url_report;
		private string _url_mo;
		private string _authkey;
		private string _admin_name;
		private DateTime? _admin_time;
		private int _is_m;
		private int? _is_authkey;
		private int _closed_per;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 合作方代码
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 中文名
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// _0-开通 1-关闭
		/// </summary>
		public int coop_status
		{
			get{ return _coop_status; }
			set
			{
				this.OnPropertyValueChange(_.coop_status,_coop_status,value);
				this._coop_status=value;
			}
		}
		/// <summary>
		/// 合作日期
		/// </summary>
		public DateTime? coop_date
		{
			get{ return _coop_date; }
			set
			{
				this.OnPropertyValueChange(_.coop_date,_coop_date,value);
				this._coop_date=value;
			}
		}
		/// <summary>
		/// 合作开始时间
		/// </summary>
		public object turn_on_time
		{
			get{ return _turn_on_time; }
			set
			{
				this.OnPropertyValueChange(_.turn_on_time,_turn_on_time,value);
				this._turn_on_time=value;
			}
		}
		/// <summary>
		/// 合作关闭时间
		/// </summary>
		public object turn_off_time
		{
			get{ return _turn_off_time; }
			set
			{
				this.OnPropertyValueChange(_.turn_off_time,_turn_off_time,value);
				this._turn_off_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string url_report
		{
			get{ return _url_report; }
			set
			{
				this.OnPropertyValueChange(_.url_report,_url_report,value);
				this._url_report=value;
			}
		}
		/// <summary>
		/// 短信MO同步地址
		/// </summary>
		public string url_mo
		{
			get{ return _url_mo; }
			set
			{
				this.OnPropertyValueChange(_.url_mo,_url_mo,value);
				this._url_mo=value;
			}
		}
		/// <summary>
		/// 鉴权密钥
		/// </summary>
		public string authkey
		{
			get{ return _authkey; }
			set
			{
				this.OnPropertyValueChange(_.authkey,_authkey,value);
				this._authkey=value;
			}
		}
		/// <summary>
		/// 操作人
		/// </summary>
		public string admin_name
		{
			get{ return _admin_name; }
			set
			{
				this.OnPropertyValueChange(_.admin_name,_admin_name,value);
				this._admin_name=value;
			}
		}
		/// <summary>
		/// 操作时间
		/// </summary>
		public DateTime? admin_time
		{
			get{ return _admin_time; }
			set
			{
				this.OnPropertyValueChange(_.admin_time,_admin_time,value);
				this._admin_time=value;
			}
		}
		/// <summary>
		/// 是否同步多条：1：是；0：否
		/// </summary>
		public int is_m
		{
			get{ return _is_m; }
			set
			{
				this.OnPropertyValueChange(_.is_m,_is_m,value);
				this._is_m=value;
			}
		}
		/// <summary>
		/// _0不鉴权  1需鉴权
		/// </summary>
		public int? is_authkey
		{
			get{ return _is_authkey; }
			set
			{
				this.OnPropertyValueChange(_.is_authkey,_is_authkey,value);
				this._is_authkey=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int closed_per
		{
			get{ return _closed_per; }
			set
			{
				this.OnPropertyValueChange(_.closed_per,_closed_per,value);
				this._closed_per=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.sp_id,
				_.coop_status,
				_.coop_date,
				_.turn_on_time,
				_.turn_off_time,
				_.url_report,
				_.url_mo,
				_.authkey,
				_.admin_name,
				_.admin_time,
				_.is_m,
				_.is_authkey,
				_.closed_per};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._sp_id,
				this._coop_status,
				this._coop_date,
				this._turn_on_time,
				this._turn_off_time,
				this._url_report,
				this._url_mo,
				this._authkey,
				this._admin_name,
				this._admin_time,
				this._is_m,
				this._is_authkey,
				this._closed_per};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cp_cooperate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","cp_cooperate","id");
			/// <summary>
			/// 合作方代码
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","cp_cooperate","合作方代码");
			/// <summary>
			/// 中文名
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","cp_cooperate","中文名");
			/// <summary>
			/// _0-开通 1-关闭
			/// </summary>
			public readonly static Field coop_status = new Field("coop_status","cp_cooperate","_0-开通 1-关闭");
			/// <summary>
			/// 合作日期
			/// </summary>
			public readonly static Field coop_date = new Field("coop_date","cp_cooperate","合作日期");
			/// <summary>
			/// 合作开始时间
			/// </summary>
			public readonly static Field turn_on_time = new Field("turn_on_time","cp_cooperate","合作开始时间");
			/// <summary>
			/// 合作关闭时间
			/// </summary>
			public readonly static Field turn_off_time = new Field("turn_off_time","cp_cooperate","合作关闭时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field url_report = new Field("url_report","cp_cooperate","url_report");
			/// <summary>
			/// 短信MO同步地址
			/// </summary>
			public readonly static Field url_mo = new Field("url_mo","cp_cooperate","短信MO同步地址");
			/// <summary>
			/// 鉴权密钥
			/// </summary>
			public readonly static Field authkey = new Field("authkey","cp_cooperate","鉴权密钥");
			/// <summary>
			/// 操作人
			/// </summary>
			public readonly static Field admin_name = new Field("admin_name","cp_cooperate","操作人");
			/// <summary>
			/// 操作时间
			/// </summary>
			public readonly static Field admin_time = new Field("admin_time","cp_cooperate","操作时间");
			/// <summary>
			/// 是否同步多条：1：是；0：否
			/// </summary>
			public readonly static Field is_m = new Field("is_m","cp_cooperate","是否同步多条：1：是；0：否");
			/// <summary>
			/// _0不鉴权  1需鉴权
			/// </summary>
			public readonly static Field is_authkey = new Field("is_authkey","cp_cooperate","_0不鉴权  1需鉴权");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field closed_per = new Field("closed_per","cp_cooperate","closed_per");
		}
		#endregion


	}
}

