//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类cp_service_type 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("cp_service_type")]
	[Serializable]
	public partial class cp_service_type : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _sp_id;
		private int? _status;
		private DateTime? _start_date;
		private string _authkey;
		private int? _is_authkey;
		private string _service_type;
		private string _add_user;
		private DateTime? _add_time;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// _1 开通 2关闭
		/// </summary>
		public int? status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 开始合作日期
		/// </summary>
		public DateTime? start_date
		{
			get{ return _start_date; }
			set
			{
				this.OnPropertyValueChange(_.start_date,_start_date,value);
				this._start_date=value;
			}
		}
		/// <summary>
		/// 鉴权密钥
		/// </summary>
		public string authkey
		{
			get{ return _authkey; }
			set
			{
				this.OnPropertyValueChange(_.authkey,_authkey,value);
				this._authkey=value;
			}
		}
		/// <summary>
		/// _1 需鉴权 2无需鉴权
		/// </summary>
		public int? is_authkey
		{
			get{ return _is_authkey; }
			set
			{
				this.OnPropertyValueChange(_.is_authkey,_is_authkey,value);
				this._is_authkey=value;
			}
		}
		/// <summary>
		/// 业务类型
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 添加人
		/// </summary>
		public string add_user
		{
			get{ return _add_user; }
			set
			{
				this.OnPropertyValueChange(_.add_user,_add_user,value);
				this._add_user=value;
			}
		}
		/// <summary>
		/// 添加时间
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.sp_id,
				_.status,
				_.start_date,
				_.authkey,
				_.is_authkey,
				_.service_type,
				_.add_user,
				_.add_time};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._sp_id,
				this._status,
				this._start_date,
				this._authkey,
				this._is_authkey,
				this._service_type,
				this._add_user,
				this._add_time};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cp_service_type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","cp_service_type","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","cp_service_type","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","cp_service_type","sp_id");
			/// <summary>
			/// _1 开通 2关闭
			/// </summary>
			public readonly static Field status = new Field("status","cp_service_type","_1 开通 2关闭");
			/// <summary>
			/// 开始合作日期
			/// </summary>
			public readonly static Field start_date = new Field("start_date","cp_service_type","开始合作日期");
			/// <summary>
			/// 鉴权密钥
			/// </summary>
			public readonly static Field authkey = new Field("authkey","cp_service_type","鉴权密钥");
			/// <summary>
			/// _1 需鉴权 2无需鉴权
			/// </summary>
			public readonly static Field is_authkey = new Field("is_authkey","cp_service_type","_1 需鉴权 2无需鉴权");
			/// <summary>
			/// 业务类型
			/// </summary>
			public readonly static Field service_type = new Field("service_type","cp_service_type","业务类型");
			/// <summary>
			/// 添加人
			/// </summary>
			public readonly static Field add_user = new Field("add_user","cp_service_type","添加人");
			/// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field add_time = new Field("add_time","cp_service_type","添加时间");
		}
		#endregion


	}
}

