//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类daily_channel_report_view 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("daily_channel_report_view")]
	[Serializable]
	public partial class daily_channel_report_view : Entity 
	{
		#region Model
		private int? _income;
		private string _cp_id;
		private string _sp_id;
		private string _appid;
		private string _paycode;
		private int? _nums;
		private DateTime? _tj_date;
		private int? _type;
		private string _province_id;
		/// <summary>
		/// 
		/// </summary>
		public int? income
		{
			get{ return _income; }
			set
			{
				this.OnPropertyValueChange(_.income,_income,value);
				this._income=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? nums
		{
			get{ return _nums; }
			set
			{
				this.OnPropertyValueChange(_.nums,_nums,value);
				this._nums=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? tj_date
		{
			get{ return _tj_date; }
			set
			{
				this.OnPropertyValueChange(_.tj_date,_tj_date,value);
				this._tj_date=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange(_.type,_type,value);
				this._type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.income,
				_.cp_id,
				_.sp_id,
				_.appid,
				_.paycode,
				_.nums,
				_.tj_date,
				_.type,
				_.province_id};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._income,
				this._cp_id,
				this._sp_id,
				this._appid,
				this._paycode,
				this._nums,
				this._tj_date,
				this._type,
				this._province_id};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","daily_channel_report_view");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field income = new Field("income","daily_channel_report_view","income");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","daily_channel_report_view","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","daily_channel_report_view","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","daily_channel_report_view","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","daily_channel_report_view","paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field nums = new Field("nums","daily_channel_report_view","nums");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tj_date = new Field("tj_date","daily_channel_report_view","tj_date");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type","daily_channel_report_view","type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","daily_channel_report_view","province_id");
		}
		#endregion


	}
}

