//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类datereport_ts_info_copy 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("datereport_ts_info_copy")]
	[Serializable]
	public partial class datereport_ts_info_copy : Entity 
	{
		#region Model
		private int _id;
		private DateTime? _tsdate;
		private DateTime? _orderdate;
		private string _province;
		private int? _price;
		private string _cpname;
		private string _cpn;
		private string _channel_sub;
		private string _channel_main;
		private string _product_name;
		private string _service_type;
		private DateTime? _add_time;
		private string _add_name;
		private string _cp_id;
		private string _sp_id;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 投诉归档时间
		/// </summary>
		public DateTime? tsdate
		{
			get{ return _tsdate; }
			set
			{
				this.OnPropertyValueChange(_.tsdate,_tsdate,value);
				this._tsdate=value;
			}
		}
		/// <summary>
		/// 订购时间
		/// </summary>
		public DateTime? orderdate
		{
			get{ return _orderdate; }
			set
			{
				this.OnPropertyValueChange(_.orderdate,_orderdate,value);
				this._orderdate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province
		{
			get{ return _province; }
			set
			{
				this.OnPropertyValueChange(_.province,_province,value);
				this._province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cpname
		{
			get{ return _cpname; }
			set
			{
				this.OnPropertyValueChange(_.cpname,_cpname,value);
				this._cpname=value;
			}
		}
		/// <summary>
		/// 投诉号码
		/// </summary>
		public string cpn
		{
			get{ return _cpn; }
			set
			{
				this.OnPropertyValueChange(_.cpn,_cpn,value);
				this._cpn=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_sub
		{
			get{ return _channel_sub; }
			set
			{
				this.OnPropertyValueChange(_.channel_sub,_channel_sub,value);
				this._channel_sub=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_main
		{
			get{ return _channel_main; }
			set
			{
				this.OnPropertyValueChange(_.channel_main,_channel_main,value);
				this._channel_main=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string add_name
		{
			get{ return _add_name; }
			set
			{
				this.OnPropertyValueChange(_.add_name,_add_name,value);
				this._add_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.tsdate,
				_.orderdate,
				_.province,
				_.price,
				_.cpname,
				_.cpn,
				_.channel_sub,
				_.channel_main,
				_.product_name,
				_.service_type,
				_.add_time,
				_.add_name,
				_.cp_id,
				_.sp_id};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._tsdate,
				this._orderdate,
				this._province,
				this._price,
				this._cpname,
				this._cpn,
				this._channel_sub,
				this._channel_main,
				this._product_name,
				this._service_type,
				this._add_time,
				this._add_name,
				this._cp_id,
				this._sp_id};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","datereport_ts_info_copy");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","datereport_ts_info_copy","id");
			/// <summary>
			/// 投诉归档时间
			/// </summary>
			public readonly static Field tsdate = new Field("tsdate","datereport_ts_info_copy","投诉归档时间");
			/// <summary>
			/// 订购时间
			/// </summary>
			public readonly static Field orderdate = new Field("orderdate","datereport_ts_info_copy","订购时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province = new Field("province","datereport_ts_info_copy","province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","datereport_ts_info_copy","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cpname = new Field("cpname","datereport_ts_info_copy","cpname");
			/// <summary>
			/// 投诉号码
			/// </summary>
			public readonly static Field cpn = new Field("cpn","datereport_ts_info_copy","投诉号码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_sub = new Field("channel_sub","datereport_ts_info_copy","channel_sub");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_main = new Field("channel_main","datereport_ts_info_copy","channel_main");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","datereport_ts_info_copy","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_type = new Field("service_type","datereport_ts_info_copy","service_type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_time = new Field("add_time","datereport_ts_info_copy","add_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_name = new Field("add_name","datereport_ts_info_copy","add_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","datereport_ts_info_copy","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","datereport_ts_info_copy","sp_id");
		}
		#endregion


	}
}

