//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类datereport_qdb_upload_temp 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("datereport_qdb_upload_temp")]
	[Serializable]
	public partial class datereport_qdb_upload_temp : Entity 
	{
		#region Model
		private int _id;
		private DateTime? _tjdate;
		private string _province;
		private string _product_name;
		private string _spname;
		private int? _income;
		private int? _price;
		private string _service_type;
		private DateTime? _add_time;
		private string _add_name;
		private string _ch_name;
		private string _ch_id;
		private int? _new_user;
		private int? _new_income;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 统计时间
		/// </summary>
		public DateTime? tjdate
		{
			get{ return _tjdate; }
			set
			{
				this.OnPropertyValueChange(_.tjdate,_tjdate,value);
				this._tjdate=value;
			}
		}
		/// <summary>
		/// 省份
		/// </summary>
		public string province
		{
			get{ return _province; }
			set
			{
				this.OnPropertyValueChange(_.province,_province,value);
				this._province=value;
			}
		}
		/// <summary>
		/// 业务名称
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 主渠道名称
		/// </summary>
		public string spname
		{
			get{ return _spname; }
			set
			{
				this.OnPropertyValueChange(_.spname,_spname,value);
				this._spname=value;
			}
		}
		/// <summary>
		/// 收入
		/// </summary>
		public int? income
		{
			get{ return _income; }
			set
			{
				this.OnPropertyValueChange(_.income,_income,value);
				this._income=value;
			}
		}
		/// <summary>
		/// 单价
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// SDK类型
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 导入时间
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		/// <summary>
		/// 导入人
		/// </summary>
		public string add_name
		{
			get{ return _add_name; }
			set
			{
				this.OnPropertyValueChange(_.add_name,_add_name,value);
				this._add_name=value;
			}
		}
		/// <summary>
		/// 渠道名称
		/// </summary>
		public string ch_name
		{
			get{ return _ch_name; }
			set
			{
				this.OnPropertyValueChange(_.ch_name,_ch_name,value);
				this._ch_name=value;
			}
		}
		/// <summary>
		/// 渠道id
		/// </summary>
		public string ch_id
		{
			get{ return _ch_id; }
			set
			{
				this.OnPropertyValueChange(_.ch_id,_ch_id,value);
				this._ch_id=value;
			}
		}
		/// <summary>
		/// 新增用户数
		/// </summary>
		public int? new_user
		{
			get{ return _new_user; }
			set
			{
				this.OnPropertyValueChange(_.new_user,_new_user,value);
				this._new_user=value;
			}
		}
		/// <summary>
		/// 新增收入
		/// </summary>
		public int? new_income
		{
			get{ return _new_income; }
			set
			{
				this.OnPropertyValueChange(_.new_income,_new_income,value);
				this._new_income=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.tjdate,
				_.province,
				_.product_name,
				_.spname,
				_.income,
				_.price,
				_.service_type,
				_.add_time,
				_.add_name,
				_.ch_name,
				_.ch_id,
				_.new_user,
				_.new_income};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._tjdate,
				this._province,
				this._product_name,
				this._spname,
				this._income,
				this._price,
				this._service_type,
				this._add_time,
				this._add_name,
				this._ch_name,
				this._ch_id,
				this._new_user,
				this._new_income};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","datereport_qdb_upload_temp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","datereport_qdb_upload_temp","id");
			/// <summary>
			/// 统计时间
			/// </summary>
			public readonly static Field tjdate = new Field("tjdate","datereport_qdb_upload_temp","统计时间");
			/// <summary>
			/// 省份
			/// </summary>
			public readonly static Field province = new Field("province","datereport_qdb_upload_temp","省份");
			/// <summary>
			/// 业务名称
			/// </summary>
			public readonly static Field product_name = new Field("product_name","datereport_qdb_upload_temp","业务名称");
			/// <summary>
			/// 主渠道名称
			/// </summary>
			public readonly static Field spname = new Field("spname","datereport_qdb_upload_temp","主渠道名称");
			/// <summary>
			/// 收入
			/// </summary>
			public readonly static Field income = new Field("income","datereport_qdb_upload_temp","收入");
			/// <summary>
			/// 单价
			/// </summary>
			public readonly static Field price = new Field("price","datereport_qdb_upload_temp","单价");
			/// <summary>
			/// SDK类型
			/// </summary>
			public readonly static Field service_type = new Field("service_type","datereport_qdb_upload_temp","SDK类型");
			/// <summary>
			/// 导入时间
			/// </summary>
			public readonly static Field add_time = new Field("add_time","datereport_qdb_upload_temp","导入时间");
			/// <summary>
			/// 导入人
			/// </summary>
			public readonly static Field add_name = new Field("add_name","datereport_qdb_upload_temp","导入人");
			/// <summary>
			/// 渠道名称
			/// </summary>
			public readonly static Field ch_name = new Field("ch_name","datereport_qdb_upload_temp","渠道名称");
			/// <summary>
			/// 渠道id
			/// </summary>
			public readonly static Field ch_id = new Field("ch_id","datereport_qdb_upload_temp","渠道id");
			/// <summary>
			/// 新增用户数
			/// </summary>
			public readonly static Field new_user = new Field("new_user","datereport_qdb_upload_temp","新增用户数");
			/// <summary>
			/// 新增收入
			/// </summary>
			public readonly static Field new_income = new Field("new_income","datereport_qdb_upload_temp","新增收入");
		}
		#endregion


	}
}

