//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类datereport_upload_copy 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("datereport_upload_copy")]
	[Serializable]
	public partial class datereport_upload_copy : Entity 
	{
		#region Model
		private int _id;
		private DateTime? _tjdate;
		private string _app_id;
		private string _province;
		private string _product_name;
		private string _spname;
		private int? _income;
		private int? _fee_num;
		private int? _fee_user;
		private int? _price;
		private string _service_type;
		private DateTime? _add_time;
		private string _add_name;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 统计时间
		/// </summary>
		public DateTime? tjdate
		{
			get{ return _tjdate; }
			set
			{
				this.OnPropertyValueChange(_.tjdate,_tjdate,value);
				this._tjdate=value;
			}
		}
		/// <summary>
		/// 应用id
		/// </summary>
		public string app_id
		{
			get{ return _app_id; }
			set
			{
				this.OnPropertyValueChange(_.app_id,_app_id,value);
				this._app_id=value;
			}
		}
		/// <summary>
		/// 运用id
		/// </summary>
		public string province
		{
			get{ return _province; }
			set
			{
				this.OnPropertyValueChange(_.province,_province,value);
				this._province=value;
			}
		}
		/// <summary>
		/// 运用名称
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 主渠道名称
		/// </summary>
		public string spname
		{
			get{ return _spname; }
			set
			{
				this.OnPropertyValueChange(_.spname,_spname,value);
				this._spname=value;
			}
		}
		/// <summary>
		/// 收入
		/// </summary>
		public int? income
		{
			get{ return _income; }
			set
			{
				this.OnPropertyValueChange(_.income,_income,value);
				this._income=value;
			}
		}
		/// <summary>
		/// 付费次数
		/// </summary>
		public int? fee_num
		{
			get{ return _fee_num; }
			set
			{
				this.OnPropertyValueChange(_.fee_num,_fee_num,value);
				this._fee_num=value;
			}
		}
		/// <summary>
		/// 付费用户数
		/// </summary>
		public int? fee_user
		{
			get{ return _fee_user; }
			set
			{
				this.OnPropertyValueChange(_.fee_user,_fee_user,value);
				this._fee_user=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// SDK类型
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 导入时间
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		/// <summary>
		/// 导入人
		/// </summary>
		public string add_name
		{
			get{ return _add_name; }
			set
			{
				this.OnPropertyValueChange(_.add_name,_add_name,value);
				this._add_name=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.tjdate,
				_.app_id,
				_.province,
				_.product_name,
				_.spname,
				_.income,
				_.fee_num,
				_.fee_user,
				_.price,
				_.service_type,
				_.add_time,
				_.add_name};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._tjdate,
				this._app_id,
				this._province,
				this._product_name,
				this._spname,
				this._income,
				this._fee_num,
				this._fee_user,
				this._price,
				this._service_type,
				this._add_time,
				this._add_name};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","datereport_upload_copy");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","datereport_upload_copy","id");
			/// <summary>
			/// 统计时间
			/// </summary>
			public readonly static Field tjdate = new Field("tjdate","datereport_upload_copy","统计时间");
			/// <summary>
			/// 应用id
			/// </summary>
			public readonly static Field app_id = new Field("app_id","datereport_upload_copy","应用id");
			/// <summary>
			/// 运用id
			/// </summary>
			public readonly static Field province = new Field("province","datereport_upload_copy","运用id");
			/// <summary>
			/// 运用名称
			/// </summary>
			public readonly static Field product_name = new Field("product_name","datereport_upload_copy","运用名称");
			/// <summary>
			/// 主渠道名称
			/// </summary>
			public readonly static Field spname = new Field("spname","datereport_upload_copy","主渠道名称");
			/// <summary>
			/// 收入
			/// </summary>
			public readonly static Field income = new Field("income","datereport_upload_copy","收入");
			/// <summary>
			/// 付费次数
			/// </summary>
			public readonly static Field fee_num = new Field("fee_num","datereport_upload_copy","付费次数");
			/// <summary>
			/// 付费用户数
			/// </summary>
			public readonly static Field fee_user = new Field("fee_user","datereport_upload_copy","付费用户数");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","datereport_upload_copy","price");
			/// <summary>
			/// SDK类型
			/// </summary>
			public readonly static Field service_type = new Field("service_type","datereport_upload_copy","SDK类型");
			/// <summary>
			/// 导入时间
			/// </summary>
			public readonly static Field add_time = new Field("add_time","datereport_upload_copy","导入时间");
			/// <summary>
			/// 导入人
			/// </summary>
			public readonly static Field add_name = new Field("add_name","datereport_upload_copy","导入人");
		}
		#endregion


	}
}

