//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类ddo_record 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ddo_record")]
	[Serializable]
	public partial class ddo_record : Entity 
	{
		#region Model
		private int _id;
		private string _msgtype;
		private string _tradeid;
		private string _paycode;
		private string _appid;
		private string _channelid;
		private string _subsid;
		private int _cost;
		private string _chargetime;
		private string _exdata;
		private string _sp_id;
		private string _cp_id;
		private int? _report_stat;
		private int? _report_times;
		private int? _status;
		private int _subcose;
		private string _subtime;
		private string _phone;
		private string _province_id;
		private string _area_code;
		private string _substat;
		private int _closed_stat;
		private string _seqId;
		private string _req_message;
		private string _code_message;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 消息类型
		/// </summary>
		public string msgtype
		{
			get{ return _msgtype; }
			set
			{
				this.OnPropertyValueChange(_.msgtype,_msgtype,value);
				this._msgtype=value;
			}
		}
		/// <summary>
		/// 交易标识
		/// </summary>
		public string tradeid
		{
			get{ return _tradeid; }
			set
			{
				this.OnPropertyValueChange(_.tradeid,_tradeid,value);
				this._tradeid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 应用id
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 渠道商代码
		/// </summary>
		public string channelid
		{
			get{ return _channelid; }
			set
			{
				this.OnPropertyValueChange(_.channelid,_channelid,value);
				this._channelid=value;
			}
		}
		/// <summary>
		/// 用户标识，为伪码
		/// </summary>
		public string subsid
		{
			get{ return _subsid; }
			set
			{
				this.OnPropertyValueChange(_.subsid,_subsid,value);
				this._subsid=value;
			}
		}
		/// <summary>
		/// 消费金额，单位为：分
		/// </summary>
		public int cost
		{
			get{ return _cost; }
			set
			{
				this.OnPropertyValueChange(_.cost,_cost,value);
				this._cost=value;
			}
		}
		/// <summary>
		/// 扣费时间
		/// </summary>
		public string chargetime
		{
			get{ return _chargetime; }
			set
			{
				this.OnPropertyValueChange(_.chargetime,_chargetime,value);
				this._chargetime=value;
			}
		}
		/// <summary>
		/// 用户自定义数据，由AP选填
		/// </summary>
		public string exdata
		{
			get{ return _exdata; }
			set
			{
				this.OnPropertyValueChange(_.exdata,_exdata,value);
				this._exdata=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// _0 未发送 1已发送
		/// </summary>
		public int? report_stat
		{
			get{ return _report_stat; }
			set
			{
				this.OnPropertyValueChange(_.report_stat,_report_stat,value);
				this._report_stat=value;
			}
		}
		/// <summary>
		/// 发送给合作方次数
		/// </summary>
		public int? report_times
		{
			get{ return _report_times; }
			set
			{
				this.OnPropertyValueChange(_.report_times,_report_times,value);
				this._report_times=value;
			}
		}
		/// <summary>
		/// _0 发起计费请求  1 计费成功请求
		/// </summary>
		public int? status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 请求金额
		/// </summary>
		public int subcose
		{
			get{ return _subcose; }
			set
			{
				this.OnPropertyValueChange(_.subcose,_subcose,value);
				this._subcose=value;
			}
		}
		/// <summary>
		/// 请求时间
		/// </summary>
		public string subtime
		{
			get{ return _subtime; }
			set
			{
				this.OnPropertyValueChange(_.subtime,_subtime,value);
				this._subtime=value;
			}
		}
		/// <summary>
		/// 手机号码
		/// </summary>
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange(_.phone,_phone,value);
				this._phone=value;
			}
		}
		/// <summary>
		/// 省份代码
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 城市代码
		/// </summary>
		public string area_code
		{
			get{ return _area_code; }
			set
			{
				this.OnPropertyValueChange(_.area_code,_area_code,value);
				this._area_code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string substat
		{
			get{ return _substat; }
			set
			{
				this.OnPropertyValueChange(_.substat,_substat,value);
				this._substat=value;
			}
		}
		/// <summary>
		/// _0不核减  1核减
		/// </summary>
		public int closed_stat
		{
			get{ return _closed_stat; }
			set
			{
				this.OnPropertyValueChange(_.closed_stat,_closed_stat,value);
				this._closed_stat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string seqId
		{
			get{ return _seqId; }
			set
			{
				this.OnPropertyValueChange(_.seqId,_seqId,value);
				this._seqId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string req_message
		{
			get{ return _req_message; }
			set
			{
				this.OnPropertyValueChange(_.req_message,_req_message,value);
				this._req_message=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string code_message
		{
			get{ return _code_message; }
			set
			{
				this.OnPropertyValueChange(_.code_message,_code_message,value);
				this._code_message=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.msgtype,
				_.tradeid,
				_.paycode,
				_.appid,
				_.channelid,
				_.subsid,
				_.cost,
				_.chargetime,
				_.exdata,
				_.sp_id,
				_.cp_id,
				_.report_stat,
				_.report_times,
				_.status,
				_.subcose,
				_.subtime,
				_.phone,
				_.province_id,
				_.area_code,
				_.substat,
				_.closed_stat,
				_.seqId,
				_.req_message,
				_.code_message};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._msgtype,
				this._tradeid,
				this._paycode,
				this._appid,
				this._channelid,
				this._subsid,
				this._cost,
				this._chargetime,
				this._exdata,
				this._sp_id,
				this._cp_id,
				this._report_stat,
				this._report_times,
				this._status,
				this._subcose,
				this._subtime,
				this._phone,
				this._province_id,
				this._area_code,
				this._substat,
				this._closed_stat,
				this._seqId,
				this._req_message,
				this._code_message};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ddo_record");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","ddo_record","id");
			/// <summary>
			/// 消息类型
			/// </summary>
			public readonly static Field msgtype = new Field("msgtype","ddo_record","消息类型");
			/// <summary>
			/// 交易标识
			/// </summary>
			public readonly static Field tradeid = new Field("tradeid","ddo_record","交易标识");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","ddo_record","paycode");
			/// <summary>
			/// 应用id
			/// </summary>
			public readonly static Field appid = new Field("appid","ddo_record","应用id");
			/// <summary>
			/// 渠道商代码
			/// </summary>
			public readonly static Field channelid = new Field("channelid","ddo_record","渠道商代码");
			/// <summary>
			/// 用户标识，为伪码
			/// </summary>
			public readonly static Field subsid = new Field("subsid","ddo_record","用户标识，为伪码");
			/// <summary>
			/// 消费金额，单位为：分
			/// </summary>
			public readonly static Field cost = new Field("cost","ddo_record","消费金额，单位为：分");
			/// <summary>
			/// 扣费时间
			/// </summary>
			public readonly static Field chargetime = new Field("chargetime","ddo_record","扣费时间");
			/// <summary>
			/// 用户自定义数据，由AP选填
			/// </summary>
			public readonly static Field exdata = new Field("exdata","ddo_record","用户自定义数据，由AP选填");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","ddo_record","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","ddo_record","cp_id");
			/// <summary>
			/// _0 未发送 1已发送
			/// </summary>
			public readonly static Field report_stat = new Field("report_stat","ddo_record","_0 未发送 1已发送");
			/// <summary>
			/// 发送给合作方次数
			/// </summary>
			public readonly static Field report_times = new Field("report_times","ddo_record","发送给合作方次数");
			/// <summary>
			/// _0 发起计费请求  1 计费成功请求
			/// </summary>
			public readonly static Field status = new Field("status","ddo_record","_0 发起计费请求  1 计费成功请求");
			/// <summary>
			/// 请求金额
			/// </summary>
			public readonly static Field subcose = new Field("subcose","ddo_record","请求金额");
			/// <summary>
			/// 请求时间
			/// </summary>
			public readonly static Field subtime = new Field("subtime","ddo_record","请求时间");
			/// <summary>
			/// 手机号码
			/// </summary>
			public readonly static Field phone = new Field("phone","ddo_record","手机号码");
			/// <summary>
			/// 省份代码
			/// </summary>
			public readonly static Field province_id = new Field("province_id","ddo_record","省份代码");
			/// <summary>
			/// 城市代码
			/// </summary>
			public readonly static Field area_code = new Field("area_code","ddo_record","城市代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field substat = new Field("substat","ddo_record","substat");
			/// <summary>
			/// _0不核减  1核减
			/// </summary>
			public readonly static Field closed_stat = new Field("closed_stat","ddo_record","_0不核减  1核减");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field seqId = new Field("seqId","ddo_record","seqId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field req_message = new Field("req_message","ddo_record","req_message");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field code_message = new Field("code_message","ddo_record","code_message");
		}
		#endregion


	}
}

