//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类dept 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("dept")]
	[Serializable]
	public partial class dept : Entity 
	{
		#region Model
		private short _id;
		private string _name;
		private int? _sort;
		private int? _ispir;
		private DateTime? _indate;
		/// <summary>
		/// 
		/// </summary>
		public short id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 组名
		/// </summary>
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange(_.name,_name,value);
				this._name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? sort
		{
			get{ return _sort; }
			set
			{
				this.OnPropertyValueChange(_.sort,_sort,value);
				this._sort=value;
			}
		}
		/// <summary>
		/// 是否权限验证
		/// </summary>
		public int? ispir
		{
			get{ return _ispir; }
			set
			{
				this.OnPropertyValueChange(_.ispir,_ispir,value);
				this._ispir=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? indate
		{
			get{ return _indate; }
			set
			{
				this.OnPropertyValueChange(_.indate,_indate,value);
				this._indate=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.name,
				_.sort,
				_.ispir,
				_.indate};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._name,
				this._sort,
				this._ispir,
				this._indate};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","dept");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","dept","id");
			/// <summary>
			/// 组名
			/// </summary>
			public readonly static Field name = new Field("name","dept","组名");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sort = new Field("sort","dept","sort");
			/// <summary>
			/// 是否权限验证
			/// </summary>
			public readonly static Field ispir = new Field("ispir","dept","是否权限验证");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field indate = new Field("indate","dept","indate");
		}
		#endregion


	}
}

