//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类ip_num 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ip_num")]
	[Serializable]
	public partial class ip_num : Entity 
	{
		#region Model
		private int _id;
		private string _a1;
		private string _a2;
		private string _a3;
		private string _a4;
		private string _b1;
		private string _b2;
		private string _b3;
		private string _b4;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string a1
		{
			get{ return _a1; }
			set
			{
				this.OnPropertyValueChange(_.a1,_a1,value);
				this._a1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string a2
		{
			get{ return _a2; }
			set
			{
				this.OnPropertyValueChange(_.a2,_a2,value);
				this._a2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string a3
		{
			get{ return _a3; }
			set
			{
				this.OnPropertyValueChange(_.a3,_a3,value);
				this._a3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string a4
		{
			get{ return _a4; }
			set
			{
				this.OnPropertyValueChange(_.a4,_a4,value);
				this._a4=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string b1
		{
			get{ return _b1; }
			set
			{
				this.OnPropertyValueChange(_.b1,_b1,value);
				this._b1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string b2
		{
			get{ return _b2; }
			set
			{
				this.OnPropertyValueChange(_.b2,_b2,value);
				this._b2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string b3
		{
			get{ return _b3; }
			set
			{
				this.OnPropertyValueChange(_.b3,_b3,value);
				this._b3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string b4
		{
			get{ return _b4; }
			set
			{
				this.OnPropertyValueChange(_.b4,_b4,value);
				this._b4=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.a1,
				_.a2,
				_.a3,
				_.a4,
				_.b1,
				_.b2,
				_.b3,
				_.b4};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._a1,
				this._a2,
				this._a3,
				this._a4,
				this._b1,
				this._b2,
				this._b3,
				this._b4};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ip_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","ip_num","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field a1 = new Field("a1","ip_num","a1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field a2 = new Field("a2","ip_num","a2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field a3 = new Field("a3","ip_num","a3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field a4 = new Field("a4","ip_num","a4");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field b1 = new Field("b1","ip_num","b1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field b2 = new Field("b2","ip_num","b2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field b3 = new Field("b3","ip_num","b3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field b4 = new Field("b4","ip_num","b4");
		}
		#endregion


	}
}

