//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类log 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("log")]
	[Serializable]
	public partial class log : Entity 
	{
		#region Model
		private int _id;
		private int? _level;
		private string _memo;
		private DateTime? _indate;
		private string _type;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? level
		{
			get{ return _level; }
			set
			{
				this.OnPropertyValueChange(_.level,_level,value);
				this._level=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string memo
		{
			get{ return _memo; }
			set
			{
				this.OnPropertyValueChange(_.memo,_memo,value);
				this._memo=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? indate
		{
			get{ return _indate; }
			set
			{
				this.OnPropertyValueChange(_.indate,_indate,value);
				this._indate=value;
			}
		}
		/// <summary>
		/// 类型
		/// </summary>
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange(_.type,_type,value);
				this._type=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.level,
				_.memo,
				_.indate,
				_.type};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._level,
				this._memo,
				this._indate,
				this._type};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","log");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","log","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field level = new Field("level","log","level");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field memo = new Field("memo","log","memo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field indate = new Field("indate","log","indate");
			/// <summary>
			/// 类型
			/// </summary>
			public readonly static Field type = new Field("type","log","类型");
		}
		#endregion


	}
}

