//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类mobile_miscid 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("mobile_miscid")]
	[Serializable]
	public partial class mobile_miscid : Entity 
	{
		#region Model
		private int _id;
		private string _mobile;
		private string _province;
		private string _city;
		private string _postcode;
		private string _miscid;
		private string _oper;
		private DateTime _updatetime;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string mobile
		{
			get{ return _mobile; }
			set
			{
				this.OnPropertyValueChange(_.mobile,_mobile,value);
				this._mobile=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province
		{
			get{ return _province; }
			set
			{
				this.OnPropertyValueChange(_.province,_province,value);
				this._province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string city
		{
			get{ return _city; }
			set
			{
				this.OnPropertyValueChange(_.city,_city,value);
				this._city=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string postcode
		{
			get{ return _postcode; }
			set
			{
				this.OnPropertyValueChange(_.postcode,_postcode,value);
				this._postcode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string miscid
		{
			get{ return _miscid; }
			set
			{
				this.OnPropertyValueChange(_.miscid,_miscid,value);
				this._miscid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string oper
		{
			get{ return _oper; }
			set
			{
				this.OnPropertyValueChange(_.oper,_oper,value);
				this._oper=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime updatetime
		{
			get{ return _updatetime; }
			set
			{
				this.OnPropertyValueChange(_.updatetime,_updatetime,value);
				this._updatetime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.mobile,
				_.province,
				_.city,
				_.postcode,
				_.miscid,
				_.oper,
				_.updatetime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._mobile,
				this._province,
				this._city,
				this._postcode,
				this._miscid,
				this._oper,
				this._updatetime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","mobile_miscid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","mobile_miscid","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mobile = new Field("mobile","mobile_miscid","mobile");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province = new Field("province","mobile_miscid","province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field city = new Field("city","mobile_miscid","city");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field postcode = new Field("postcode","mobile_miscid","postcode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field miscid = new Field("miscid","mobile_miscid","miscid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field oper = new Field("oper","mobile_miscid","oper");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field updatetime = new Field("updatetime","mobile_miscid","updatetime");
		}
		#endregion


	}
}

