//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类phone_pwd 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("phone_pwd")]
	[Serializable]
	public partial class phone_pwd : Entity 
	{
		#region Model
		private int _id;
		private string _phone;
		private string _password;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange(_.phone,_phone,value);
				this._phone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string password
		{
			get{ return _password; }
			set
			{
				this.OnPropertyValueChange(_.password,_password,value);
				this._password=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.phone,
				_.password};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._phone,
				this._password};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","phone_pwd");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","phone_pwd","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone","phone_pwd","phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field password = new Field("password","phone_pwd","password");
		}
		#endregion


	}
}

