//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类pj_app_fee 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pj_app_fee")]
	[Serializable]
	public partial class pj_app_fee : Entity 
	{
		#region Model
		private int _id;
		private string _app_id;
		private int? _price;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_id
		{
			get{ return _app_id; }
			set
			{
				this.OnPropertyValueChange(_.app_id,_app_id,value);
				this._app_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.app_id,
				_.price};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._app_id,
				this._price};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","pj_app_fee");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","pj_app_fee","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_id = new Field("app_id","pj_app_fee","app_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","pj_app_fee","price");
		}
		#endregion


	}
}

