//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类pj_channelid_today 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pj_channelid_today")]
	[Serializable]
	public partial class pj_channelid_today : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _channelid;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channelid
		{
			get{ return _channelid; }
			set
			{
				this.OnPropertyValueChange(_.channelid,_channelid,value);
				this._channelid=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.channelid};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._channelid};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","pj_channelid_today");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","pj_channelid_today","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","pj_channelid_today","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channelid = new Field("channelid","pj_channelid_today","channelid");
		}
		#endregion


	}
}

