//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类pj_channel_id 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pj_channel_id")]
	[Serializable]
	public partial class pj_channel_id : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _channel_id;
		private string _app_id;
		private string _channel_name;
		private string _sp_id;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_id
		{
			get{ return _channel_id; }
			set
			{
				this.OnPropertyValueChange(_.channel_id,_channel_id,value);
				this._channel_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_id
		{
			get{ return _app_id; }
			set
			{
				this.OnPropertyValueChange(_.app_id,_app_id,value);
				this._app_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_name
		{
			get{ return _channel_name; }
			set
			{
				this.OnPropertyValueChange(_.channel_name,_channel_name,value);
				this._channel_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.channel_id,
				_.app_id,
				_.channel_name,
				_.sp_id};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._channel_id,
				this._app_id,
				this._channel_name,
				this._sp_id};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","pj_channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","pj_channel_id","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","pj_channel_id","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_id = new Field("channel_id","pj_channel_id","channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_id = new Field("app_id","pj_channel_id","app_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_name = new Field("channel_name","pj_channel_id","channel_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","pj_channel_id","sp_id");
		}
		#endregion


	}
}

