//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类pj_datereport_view 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pj_datereport_view")]
	[Serializable]
	public partial class pj_datereport_view : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _channel_id;
		private int? _price;
		private DateTime? _tj_date;
		private int? _succ_nums;
		private int? _faile_nums;
		private string _miscid;
		private string _sp_id;
		private string _cp_id;
		private int? _succ_price;
		private int? _faile_price;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_id
		{
			get{ return _channel_id; }
			set
			{
				this.OnPropertyValueChange(_.channel_id,_channel_id,value);
				this._channel_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? tj_date
		{
			get{ return _tj_date; }
			set
			{
				this.OnPropertyValueChange(_.tj_date,_tj_date,value);
				this._tj_date=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? succ_nums
		{
			get{ return _succ_nums; }
			set
			{
				this.OnPropertyValueChange(_.succ_nums,_succ_nums,value);
				this._succ_nums=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? faile_nums
		{
			get{ return _faile_nums; }
			set
			{
				this.OnPropertyValueChange(_.faile_nums,_faile_nums,value);
				this._faile_nums=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string miscid
		{
			get{ return _miscid; }
			set
			{
				this.OnPropertyValueChange(_.miscid,_miscid,value);
				this._miscid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? succ_price
		{
			get{ return _succ_price; }
			set
			{
				this.OnPropertyValueChange(_.succ_price,_succ_price,value);
				this._succ_price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? faile_price
		{
			get{ return _faile_price; }
			set
			{
				this.OnPropertyValueChange(_.faile_price,_faile_price,value);
				this._faile_price=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.channel_id,
				_.price,
				_.tj_date,
				_.succ_nums,
				_.faile_nums,
				_.miscid,
				_.sp_id,
				_.cp_id,
				_.succ_price,
				_.faile_price};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._channel_id,
				this._price,
				this._tj_date,
				this._succ_nums,
				this._faile_nums,
				this._miscid,
				this._sp_id,
				this._cp_id,
				this._succ_price,
				this._faile_price};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","pj_datereport_view");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","pj_datereport_view","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","pj_datereport_view","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_id = new Field("channel_id","pj_datereport_view","channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","pj_datereport_view","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tj_date = new Field("tj_date","pj_datereport_view","tj_date");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field succ_nums = new Field("succ_nums","pj_datereport_view","succ_nums");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field faile_nums = new Field("faile_nums","pj_datereport_view","faile_nums");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field miscid = new Field("miscid","pj_datereport_view","miscid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","pj_datereport_view","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","pj_datereport_view","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field succ_price = new Field("succ_price","pj_datereport_view","succ_price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field faile_price = new Field("faile_price","pj_datereport_view","faile_price");
		}
		#endregion


	}
}

