//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类pj_hj_set 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pj_hj_set")]
	[Serializable]
	public partial class pj_hj_set : Entity 
	{
		#region Model
		private int _id;
		private string _app_id;
		private int? _price;
		private string _hour;
		private int? _hj_per;
		private string _cp_id;
		private string _sp_id;
		private string _channel_id;
		private string _dst_cp_id;
		private string _dst_sp_id;
		private string _dst_channel_id;
		private string _dst_app_id;
		private int? _dst_price;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_id
		{
			get{ return _app_id; }
			set
			{
				this.OnPropertyValueChange(_.app_id,_app_id,value);
				this._app_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string hour
		{
			get{ return _hour; }
			set
			{
				this.OnPropertyValueChange(_.hour,_hour,value);
				this._hour=value;
			}
		}
		/// <summary>
		/// 核减比例
		/// </summary>
		public int? hj_per
		{
			get{ return _hj_per; }
			set
			{
				this.OnPropertyValueChange(_.hj_per,_hj_per,value);
				this._hj_per=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_id
		{
			get{ return _channel_id; }
			set
			{
				this.OnPropertyValueChange(_.channel_id,_channel_id,value);
				this._channel_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string dst_cp_id
		{
			get{ return _dst_cp_id; }
			set
			{
				this.OnPropertyValueChange(_.dst_cp_id,_dst_cp_id,value);
				this._dst_cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string dst_sp_id
		{
			get{ return _dst_sp_id; }
			set
			{
				this.OnPropertyValueChange(_.dst_sp_id,_dst_sp_id,value);
				this._dst_sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string dst_channel_id
		{
			get{ return _dst_channel_id; }
			set
			{
				this.OnPropertyValueChange(_.dst_channel_id,_dst_channel_id,value);
				this._dst_channel_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string dst_app_id
		{
			get{ return _dst_app_id; }
			set
			{
				this.OnPropertyValueChange(_.dst_app_id,_dst_app_id,value);
				this._dst_app_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? dst_price
		{
			get{ return _dst_price; }
			set
			{
				this.OnPropertyValueChange(_.dst_price,_dst_price,value);
				this._dst_price=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.app_id,
				_.price,
				_.hour,
				_.hj_per,
				_.cp_id,
				_.sp_id,
				_.channel_id,
				_.dst_cp_id,
				_.dst_sp_id,
				_.dst_channel_id,
				_.dst_app_id,
				_.dst_price};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._app_id,
				this._price,
				this._hour,
				this._hj_per,
				this._cp_id,
				this._sp_id,
				this._channel_id,
				this._dst_cp_id,
				this._dst_sp_id,
				this._dst_channel_id,
				this._dst_app_id,
				this._dst_price};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","pj_hj_set");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","pj_hj_set","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_id = new Field("app_id","pj_hj_set","app_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","pj_hj_set","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field hour = new Field("hour","pj_hj_set","hour");
			/// <summary>
			/// 核减比例
			/// </summary>
			public readonly static Field hj_per = new Field("hj_per","pj_hj_set","核减比例");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","pj_hj_set","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","pj_hj_set","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_id = new Field("channel_id","pj_hj_set","channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dst_cp_id = new Field("dst_cp_id","pj_hj_set","dst_cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dst_sp_id = new Field("dst_sp_id","pj_hj_set","dst_sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dst_channel_id = new Field("dst_channel_id","pj_hj_set","dst_channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dst_app_id = new Field("dst_app_id","pj_hj_set","dst_app_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dst_price = new Field("dst_price","pj_hj_set","dst_price");
		}
		#endregion


	}
}

