//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类privilege 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("privilege")]
	[Serializable]
	public partial class privilege : Entity 
	{
		#region Model
		private int _id;
		private string _type;
		private int? _mid;
		private int? _sid;
		private DateTime? _indate;
		private int? _optid;
		private string _optname;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 类型
		/// </summary>
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange(_.type,_type,value);
				this._type=value;
			}
		}
		/// <summary>
		/// 主id
		/// </summary>
		public int? mid
		{
			get{ return _mid; }
			set
			{
				this.OnPropertyValueChange(_.mid,_mid,value);
				this._mid=value;
			}
		}
		/// <summary>
		/// 子id
		/// </summary>
		public int? sid
		{
			get{ return _sid; }
			set
			{
				this.OnPropertyValueChange(_.sid,_sid,value);
				this._sid=value;
			}
		}
		/// <summary>
		/// 添加时间
		/// </summary>
		public DateTime? indate
		{
			get{ return _indate; }
			set
			{
				this.OnPropertyValueChange(_.indate,_indate,value);
				this._indate=value;
			}
		}
		/// <summary>
		/// 操作人id
		/// </summary>
		public int? optid
		{
			get{ return _optid; }
			set
			{
				this.OnPropertyValueChange(_.optid,_optid,value);
				this._optid=value;
			}
		}
		/// <summary>
		/// 操作人
		/// </summary>
		public string optname
		{
			get{ return _optname; }
			set
			{
				this.OnPropertyValueChange(_.optname,_optname,value);
				this._optname=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.type,
				_.mid,
				_.sid,
				_.indate,
				_.optid,
				_.optname};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._type,
				this._mid,
				this._sid,
				this._indate,
				this._optid,
				this._optname};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","privilege");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","privilege","id");
			/// <summary>
			/// 类型
			/// </summary>
			public readonly static Field type = new Field("type","privilege","类型");
			/// <summary>
			/// 主id
			/// </summary>
			public readonly static Field mid = new Field("mid","privilege","主id");
			/// <summary>
			/// 子id
			/// </summary>
			public readonly static Field sid = new Field("sid","privilege","子id");
			/// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field indate = new Field("indate","privilege","添加时间");
			/// <summary>
			/// 操作人id
			/// </summary>
			public readonly static Field optid = new Field("optid","privilege","操作人id");
			/// <summary>
			/// 操作人
			/// </summary>
			public readonly static Field optname = new Field("optname","privilege","操作人");
		}
		#endregion


	}
}

