//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类quartz_check 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("quartz_check")]
	[Serializable]
	public partial class quartz_check : Entity 
	{
		#region Model
		private int _id;
		private string _name;
		private string _time;
		private string _url;
		private string _is_alive;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange(_.name,_name,value);
				this._name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string time
		{
			get{ return _time; }
			set
			{
				this.OnPropertyValueChange(_.time,_time,value);
				this._time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string url
		{
			get{ return _url; }
			set
			{
				this.OnPropertyValueChange(_.url,_url,value);
				this._url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string is_alive
		{
			get{ return _is_alive; }
			set
			{
				this.OnPropertyValueChange(_.is_alive,_is_alive,value);
				this._is_alive=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.name,
				_.time,
				_.url,
				_.is_alive};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._name,
				this._time,
				this._url,
				this._is_alive};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","quartz_check");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","quartz_check","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name","quartz_check","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field time = new Field("time","quartz_check","time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field url = new Field("url","quartz_check","url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field is_alive = new Field("is_alive","quartz_check","is_alive");
		}
		#endregion


	}
}

