//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类quartz_local 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("quartz_local")]
	[Serializable]
	public partial class quartz_local : Entity 
	{
		#region Model
		private int _id;
		private string _job_name;
		private string _group_name;
		private string _class_name;
		private string _is_alive;
		private string _time_exp;
		private string _start_time;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string job_name
		{
			get{ return _job_name; }
			set
			{
				this.OnPropertyValueChange(_.job_name,_job_name,value);
				this._job_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string group_name
		{
			get{ return _group_name; }
			set
			{
				this.OnPropertyValueChange(_.group_name,_group_name,value);
				this._group_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string class_name
		{
			get{ return _class_name; }
			set
			{
				this.OnPropertyValueChange(_.class_name,_class_name,value);
				this._class_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string is_alive
		{
			get{ return _is_alive; }
			set
			{
				this.OnPropertyValueChange(_.is_alive,_is_alive,value);
				this._is_alive=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string time_exp
		{
			get{ return _time_exp; }
			set
			{
				this.OnPropertyValueChange(_.time_exp,_time_exp,value);
				this._time_exp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string start_time
		{
			get{ return _start_time; }
			set
			{
				this.OnPropertyValueChange(_.start_time,_start_time,value);
				this._start_time=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.job_name,
				_.group_name,
				_.class_name,
				_.is_alive,
				_.time_exp,
				_.start_time};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._job_name,
				this._group_name,
				this._class_name,
				this._is_alive,
				this._time_exp,
				this._start_time};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","quartz_local");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","quartz_local","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field job_name = new Field("job_name","quartz_local","job_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field group_name = new Field("group_name","quartz_local","group_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field class_name = new Field("class_name","quartz_local","class_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field is_alive = new Field("is_alive","quartz_local","is_alive");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field time_exp = new Field("time_exp","quartz_local","time_exp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field start_time = new Field("start_time","quartz_local","start_time");
		}
		#endregion


	}
}

