//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类rdo_record_succ 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("rdo_record_succ")]
	[Serializable]
	public partial class rdo_record_succ : Entity 
	{
		#region Model
		private int _id;
		private string _orderid;
		private string _paycode;
		private string _phone;
		private int _cost;
		private string _subtime;
		private string _chargetime;
		private string _sp_id;
		private string _cp_id;
		private int? _report_stat;
		private int? _report_times;
		private int? _status;
		private int _subcose;
		private string _province_id;
		private string _area_code;
		private string _substat;
		private int _closed_stat;
		private string _type;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 交易标识
		/// </summary>
		public string orderid
		{
			get{ return _orderid; }
			set
			{
				this.OnPropertyValueChange(_.orderid,_orderid,value);
				this._orderid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 手机号码
		/// </summary>
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange(_.phone,_phone,value);
				this._phone=value;
			}
		}
		/// <summary>
		/// 消费金额，单位为：分
		/// </summary>
		public int cost
		{
			get{ return _cost; }
			set
			{
				this.OnPropertyValueChange(_.cost,_cost,value);
				this._cost=value;
			}
		}
		/// <summary>
		/// 请求时间
		/// </summary>
		public string subtime
		{
			get{ return _subtime; }
			set
			{
				this.OnPropertyValueChange(_.subtime,_subtime,value);
				this._subtime=value;
			}
		}
		/// <summary>
		/// 扣费时间
		/// </summary>
		public string chargetime
		{
			get{ return _chargetime; }
			set
			{
				this.OnPropertyValueChange(_.chargetime,_chargetime,value);
				this._chargetime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// _0 未发送 1已发送
		/// </summary>
		public int? report_stat
		{
			get{ return _report_stat; }
			set
			{
				this.OnPropertyValueChange(_.report_stat,_report_stat,value);
				this._report_stat=value;
			}
		}
		/// <summary>
		/// 发送给合作方次数
		/// </summary>
		public int? report_times
		{
			get{ return _report_times; }
			set
			{
				this.OnPropertyValueChange(_.report_times,_report_times,value);
				this._report_times=value;
			}
		}
		/// <summary>
		/// _0 发起计费请求  1 计费成功请求
		/// </summary>
		public int? status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 请求金额
		/// </summary>
		public int subcose
		{
			get{ return _subcose; }
			set
			{
				this.OnPropertyValueChange(_.subcose,_subcose,value);
				this._subcose=value;
			}
		}
		/// <summary>
		/// 省份代码
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 城市代码
		/// </summary>
		public string area_code
		{
			get{ return _area_code; }
			set
			{
				this.OnPropertyValueChange(_.area_code,_area_code,value);
				this._area_code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string substat
		{
			get{ return _substat; }
			set
			{
				this.OnPropertyValueChange(_.substat,_substat,value);
				this._substat=value;
			}
		}
		/// <summary>
		/// _0不核减  1核减
		/// </summary>
		public int closed_stat
		{
			get{ return _closed_stat; }
			set
			{
				this.OnPropertyValueChange(_.closed_stat,_closed_stat,value);
				this._closed_stat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange(_.type,_type,value);
				this._type=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.orderid,
				_.paycode,
				_.phone,
				_.cost,
				_.subtime,
				_.chargetime,
				_.sp_id,
				_.cp_id,
				_.report_stat,
				_.report_times,
				_.status,
				_.subcose,
				_.province_id,
				_.area_code,
				_.substat,
				_.closed_stat,
				_.type};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._orderid,
				this._paycode,
				this._phone,
				this._cost,
				this._subtime,
				this._chargetime,
				this._sp_id,
				this._cp_id,
				this._report_stat,
				this._report_times,
				this._status,
				this._subcose,
				this._province_id,
				this._area_code,
				this._substat,
				this._closed_stat,
				this._type};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","rdo_record_succ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","rdo_record_succ","id");
			/// <summary>
			/// 交易标识
			/// </summary>
			public readonly static Field orderid = new Field("orderid","rdo_record_succ","交易标识");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","rdo_record_succ","paycode");
			/// <summary>
			/// 手机号码
			/// </summary>
			public readonly static Field phone = new Field("phone","rdo_record_succ","手机号码");
			/// <summary>
			/// 消费金额，单位为：分
			/// </summary>
			public readonly static Field cost = new Field("cost","rdo_record_succ","消费金额，单位为：分");
			/// <summary>
			/// 请求时间
			/// </summary>
			public readonly static Field subtime = new Field("subtime","rdo_record_succ","请求时间");
			/// <summary>
			/// 扣费时间
			/// </summary>
			public readonly static Field chargetime = new Field("chargetime","rdo_record_succ","扣费时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","rdo_record_succ","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","rdo_record_succ","cp_id");
			/// <summary>
			/// _0 未发送 1已发送
			/// </summary>
			public readonly static Field report_stat = new Field("report_stat","rdo_record_succ","_0 未发送 1已发送");
			/// <summary>
			/// 发送给合作方次数
			/// </summary>
			public readonly static Field report_times = new Field("report_times","rdo_record_succ","发送给合作方次数");
			/// <summary>
			/// _0 发起计费请求  1 计费成功请求
			/// </summary>
			public readonly static Field status = new Field("status","rdo_record_succ","_0 发起计费请求  1 计费成功请求");
			/// <summary>
			/// 请求金额
			/// </summary>
			public readonly static Field subcose = new Field("subcose","rdo_record_succ","请求金额");
			/// <summary>
			/// 省份代码
			/// </summary>
			public readonly static Field province_id = new Field("province_id","rdo_record_succ","省份代码");
			/// <summary>
			/// 城市代码
			/// </summary>
			public readonly static Field area_code = new Field("area_code","rdo_record_succ","城市代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field substat = new Field("substat","rdo_record_succ","substat");
			/// <summary>
			/// _0不核减  1核减
			/// </summary>
			public readonly static Field closed_stat = new Field("closed_stat","rdo_record_succ","_0不核减  1核减");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type","rdo_record_succ","type");
		}
		#endregion


	}
}

