//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类sp_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("sp_info")]
	[Serializable]
	public partial class sp_info : Entity 
	{
		#region Model
		private int _id;
		private string _sp_id;
		private string _sp_name;
		private string _coop_id;
		private string _pinyin;
		private string _url_game_check;
		private string _url_game_purchase;
		private string _sourceDeviceCode;
		private string _sharedSecret;
		private string _admin_name;
		private DateTime? _admin_time;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_name
		{
			get{ return _sp_name; }
			set
			{
				this.OnPropertyValueChange(_.sp_name,_sp_name,value);
				this._sp_name=value;
			}
		}
		/// <summary>
		/// sp分配的cpid
		/// </summary>
		public string coop_id
		{
			get{ return _coop_id; }
			set
			{
				this.OnPropertyValueChange(_.coop_id,_coop_id,value);
				this._coop_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string pinyin
		{
			get{ return _pinyin; }
			set
			{
				this.OnPropertyValueChange(_.pinyin,_pinyin,value);
				this._pinyin=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string url_game_check
		{
			get{ return _url_game_check; }
			set
			{
				this.OnPropertyValueChange(_.url_game_check,_url_game_check,value);
				this._url_game_check=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string url_game_purchase
		{
			get{ return _url_game_purchase; }
			set
			{
				this.OnPropertyValueChange(_.url_game_purchase,_url_game_purchase,value);
				this._url_game_purchase=value;
			}
		}
		/// <summary>
		/// 用户名
		/// </summary>
		public string sourceDeviceCode
		{
			get{ return _sourceDeviceCode; }
			set
			{
				this.OnPropertyValueChange(_.sourceDeviceCode,_sourceDeviceCode,value);
				this._sourceDeviceCode=value;
			}
		}
		/// <summary>
		/// 用户密码
		/// </summary>
		public string sharedSecret
		{
			get{ return _sharedSecret; }
			set
			{
				this.OnPropertyValueChange(_.sharedSecret,_sharedSecret,value);
				this._sharedSecret=value;
			}
		}
		/// <summary>
		/// 操作人
		/// </summary>
		public string admin_name
		{
			get{ return _admin_name; }
			set
			{
				this.OnPropertyValueChange(_.admin_name,_admin_name,value);
				this._admin_name=value;
			}
		}
		/// <summary>
		/// 操作时间
		/// </summary>
		public DateTime? admin_time
		{
			get{ return _admin_time; }
			set
			{
				this.OnPropertyValueChange(_.admin_time,_admin_time,value);
				this._admin_time=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.sp_id,
				_.sp_name,
				_.coop_id,
				_.pinyin,
				_.url_game_check,
				_.url_game_purchase,
				_.sourceDeviceCode,
				_.sharedSecret,
				_.admin_name,
				_.admin_time};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._sp_id,
				this._sp_name,
				this._coop_id,
				this._pinyin,
				this._url_game_check,
				this._url_game_purchase,
				this._sourceDeviceCode,
				this._sharedSecret,
				this._admin_name,
				this._admin_time};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","sp_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","sp_info","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","sp_info","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_name = new Field("sp_name","sp_info","sp_name");
			/// <summary>
			/// sp分配的cpid
			/// </summary>
			public readonly static Field coop_id = new Field("coop_id","sp_info","sp分配的cpid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pinyin = new Field("pinyin","sp_info","pinyin");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field url_game_check = new Field("url_game_check","sp_info","url_game_check");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field url_game_purchase = new Field("url_game_purchase","sp_info","url_game_purchase");
			/// <summary>
			/// 用户名
			/// </summary>
			public readonly static Field sourceDeviceCode = new Field("sourceDeviceCode","sp_info","用户名");
			/// <summary>
			/// 用户密码
			/// </summary>
			public readonly static Field sharedSecret = new Field("sharedSecret","sp_info","用户密码");
			/// <summary>
			/// 操作人
			/// </summary>
			public readonly static Field admin_name = new Field("admin_name","sp_info","操作人");
			/// <summary>
			/// 操作时间
			/// </summary>
			public readonly static Field admin_time = new Field("admin_time","sp_info","操作时间");
		}
		#endregion


	}
}

