//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类status_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("status_info")]
	[Serializable]
	public partial class status_info : Entity 
	{
		#region Model
		private long _id;
		private string _code;
		private string _info;
		private string _table_name;
		private string _column;
		/// <summary>
		/// 
		/// </summary>
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 错误代码
		/// </summary>
		public string code
		{
			get{ return _code; }
			set
			{
				this.OnPropertyValueChange(_.code,_code,value);
				this._code=value;
			}
		}
		/// <summary>
		/// 错误代码注解
		/// </summary>
		public string info
		{
			get{ return _info; }
			set
			{
				this.OnPropertyValueChange(_.info,_info,value);
				this._info=value;
			}
		}
		/// <summary>
		/// 表名
		/// </summary>
		public string table_name
		{
			get{ return _table_name; }
			set
			{
				this.OnPropertyValueChange(_.table_name,_table_name,value);
				this._table_name=value;
			}
		}
		/// <summary>
		/// 状态位
		/// </summary>
		public string column
		{
			get{ return _column; }
			set
			{
				this.OnPropertyValueChange(_.column,_column,value);
				this._column=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.code,
				_.info,
				_.table_name,
				_.column};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._code,
				this._info,
				this._table_name,
				this._column};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","status_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","status_info","id");
			/// <summary>
			/// 错误代码
			/// </summary>
			public readonly static Field code = new Field("code","status_info","错误代码");
			/// <summary>
			/// 错误代码注解
			/// </summary>
			public readonly static Field info = new Field("info","status_info","错误代码注解");
			/// <summary>
			/// 表名
			/// </summary>
			public readonly static Field table_name = new Field("table_name","status_info","表名");
			/// <summary>
			/// 状态位
			/// </summary>
			public readonly static Field column = new Field("column","status_info","状态位");
		}
		#endregion


	}
}

