//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类temp_phone2 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("temp_phone2")]
	[Serializable]
	public partial class temp_phone2 : Entity 
	{
		#region Model
		private int _id;
		private string _phone;
		private string _appid;
		private string _paycode;
		private string _orderid;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange(_.phone,_phone,value);
				this._phone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string orderid
		{
			get{ return _orderid; }
			set
			{
				this.OnPropertyValueChange(_.orderid,_orderid,value);
				this._orderid=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.phone,
				_.appid,
				_.paycode,
				_.orderid};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._phone,
				this._appid,
				this._paycode,
				this._orderid};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","temp_phone2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","temp_phone2","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone","temp_phone2","phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","temp_phone2","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","temp_phone2","paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field orderid = new Field("orderid","temp_phone2","orderid");
		}
		#endregion


	}
}

