//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmCmccDdo
{

	/// <summary>
	/// 实体类temp_test_copy 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("temp_test_copy")]
	[Serializable]
	public partial class temp_test_copy : Entity 
	{
		#region Model
		private int _id;
		private string _a;
		private string _b;
		private string _c;
		private string _d;
		private string _e;
		private string _f;
		private string _g;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string a
		{
			get{ return _a; }
			set
			{
				this.OnPropertyValueChange(_.a,_a,value);
				this._a=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string b
		{
			get{ return _b; }
			set
			{
				this.OnPropertyValueChange(_.b,_b,value);
				this._b=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string c
		{
			get{ return _c; }
			set
			{
				this.OnPropertyValueChange(_.c,_c,value);
				this._c=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string d
		{
			get{ return _d; }
			set
			{
				this.OnPropertyValueChange(_.d,_d,value);
				this._d=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string e
		{
			get{ return _e; }
			set
			{
				this.OnPropertyValueChange(_.e,_e,value);
				this._e=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string f
		{
			get{ return _f; }
			set
			{
				this.OnPropertyValueChange(_.f,_f,value);
				this._f=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string g
		{
			get{ return _g; }
			set
			{
				this.OnPropertyValueChange(_.g,_g,value);
				this._g=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.a,
				_.b,
				_.c,
				_.d,
				_.e,
				_.f,
				_.g};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._a,
				this._b,
				this._c,
				this._d,
				this._e,
				this._f,
				this._g};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","temp_test_copy");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","temp_test_copy","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field a = new Field("a","temp_test_copy","a");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field b = new Field("b","temp_test_copy","b");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field c = new Field("c","temp_test_copy","c");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field d = new Field("d","temp_test_copy","d");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field e = new Field("e","temp_test_copy","e");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field f = new Field("f","temp_test_copy","f");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field g = new Field("g","temp_test_copy","g");
		}
		#endregion


	}
}

