//-----------------------------------------------------------------------
// <copyright file=" Ccategory.cs" company="xxxx Enterprises">
// * Copyright (C) 2017 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: Ccategory.cs
// * history : Created by T4 02/06/2017 00:11:30 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Dos.ORM;

namespace NQuick.DataModel
{
    /// <summary>
    /// Ccategory Entity Model
    /// </summary>    
    [Serializable]
    public class Ccategory
    {
        /// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string category_name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int parent_id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int sort { get; set; }
    }
}
