//-----------------------------------------------------------------------
// <copyright file=" dictionary.cs" company="xxxx Enterprises">
// * Copyright (C) 2017 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: dictionary.cs
// * history : Created by T4 02/06/2017 00:11:30 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Dos.ORM;

namespace NQuick.DataModel
{
    /// <summary>
    /// dictionary Entity Model
    /// </summary>    
    [Serializable]
    public class dictionary
    {
        /// <summary>
        /// 
        /// </summary>
        public int id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string value { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string group { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime date_created { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime date_updated { get; set; }
    }
}
