//-----------------------------------------------------------------------
// <copyright file=" product.cs" company="xxxx Enterprises">
// * Copyright (C) 2017 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: product.cs
// * history : Created by T4 02/06/2017 00:11:30 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Dos.ORM;

namespace NQuick.DataModel
{
    /// <summary>
    /// product Entity Model
    /// </summary>    
    [Serializable]
    public class product
    {
        /// <summary>
        /// 
        /// </summary>
        public int id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string product_name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string product_desc { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string country { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string germany_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string franch_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string Italy_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string spanish_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string japan_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string uk_amazon_url { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int main_image_id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int categoryid { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string product_specification { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string product_features { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string seo_link_text { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string seo_title { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string seo_keyword { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string seo_desc { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int is_publish { get; set; }
    }
}
