//-----------------------------------------------------------------------
// <copyright file=" user.cs" company="xxxx Enterprises">
// * Copyright (C) 2017 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: user.cs
// * history : Created by T4 02/06/2017 00:11:30 
// </copyright>
//-----------------------------------------------------------------------
using System;
using Dos.ORM;

namespace NQuick.DataModel
{
    /// <summary>
    /// user Entity Model
    /// </summary>    
    [Serializable]
    public class user
    {
        /// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string user_name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string real_name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string qq_number { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string phone { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string mobile { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string email { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string photo_path { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string password { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string hash_code { get; set; }
    
        /// <summary>
        /// 字典表的ID
        /// </summary>
        public int position_id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int is_admin { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public int company_id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public string login_token { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime last_login_time { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime create_time { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        public DateTime update_time { get; set; }
    }
}
