//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model
{

	/// <summary>
	/// 实体类high_products 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("high_products")]
	[Serializable]
	public partial class high_products : Entity 
	{
		#region Model
		private long _id;
		private string _product_id;
		private string _product_name;
		private string _main_picture;
		private string _product_detail;
		private string _shop_name;
		private string _price;
		private string _sales_amount;
		private string _percent;
		private string _salary;
		private string _status;
		private string _event_percent;
		private string _event_salary;
		private DateTime? _event_start;
		private DateTime? _event_end;
		private string _wangwang;
		private string _taoke_short_url;
		private string _taoke_url;
		private string _taoke_secretword;
		private string _coupon_amount;
		private string _coupon_remaining;
		private string _coupon_price;
		private DateTime? _coupon_start;
		private DateTime? _coupon_end;
		private string _coupon_link;
		private string _coupon_secretword;
		/// <summary>
		/// 
		/// </summary>
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_id
		{
			get{ return _product_id; }
			set
			{
				this.OnPropertyValueChange(_.product_id,_product_id,value);
				this._product_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string main_picture
		{
			get{ return _main_picture; }
			set
			{
				this.OnPropertyValueChange(_.main_picture,_main_picture,value);
				this._main_picture=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_detail
		{
			get{ return _product_detail; }
			set
			{
				this.OnPropertyValueChange(_.product_detail,_product_detail,value);
				this._product_detail=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string shop_name
		{
			get{ return _shop_name; }
			set
			{
				this.OnPropertyValueChange(_.shop_name,_shop_name,value);
				this._shop_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sales_amount
		{
			get{ return _sales_amount; }
			set
			{
				this.OnPropertyValueChange(_.sales_amount,_sales_amount,value);
				this._sales_amount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string percent
		{
			get{ return _percent; }
			set
			{
				this.OnPropertyValueChange(_.percent,_percent,value);
				this._percent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string salary
		{
			get{ return _salary; }
			set
			{
				this.OnPropertyValueChange(_.salary,_salary,value);
				this._salary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string event_percent
		{
			get{ return _event_percent; }
			set
			{
				this.OnPropertyValueChange(_.event_percent,_event_percent,value);
				this._event_percent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string event_salary
		{
			get{ return _event_salary; }
			set
			{
				this.OnPropertyValueChange(_.event_salary,_event_salary,value);
				this._event_salary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? event_start
		{
			get{ return _event_start; }
			set
			{
				this.OnPropertyValueChange(_.event_start,_event_start,value);
				this._event_start=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? event_end
		{
			get{ return _event_end; }
			set
			{
				this.OnPropertyValueChange(_.event_end,_event_end,value);
				this._event_end=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string wangwang
		{
			get{ return _wangwang; }
			set
			{
				this.OnPropertyValueChange(_.wangwang,_wangwang,value);
				this._wangwang=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string taoke_short_url
		{
			get{ return _taoke_short_url; }
			set
			{
				this.OnPropertyValueChange(_.taoke_short_url,_taoke_short_url,value);
				this._taoke_short_url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string taoke_url
		{
			get{ return _taoke_url; }
			set
			{
				this.OnPropertyValueChange(_.taoke_url,_taoke_url,value);
				this._taoke_url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string taoke_secretword
		{
			get{ return _taoke_secretword; }
			set
			{
				this.OnPropertyValueChange(_.taoke_secretword,_taoke_secretword,value);
				this._taoke_secretword=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_amount
		{
			get{ return _coupon_amount; }
			set
			{
				this.OnPropertyValueChange(_.coupon_amount,_coupon_amount,value);
				this._coupon_amount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_remaining
		{
			get{ return _coupon_remaining; }
			set
			{
				this.OnPropertyValueChange(_.coupon_remaining,_coupon_remaining,value);
				this._coupon_remaining=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_price
		{
			get{ return _coupon_price; }
			set
			{
				this.OnPropertyValueChange(_.coupon_price,_coupon_price,value);
				this._coupon_price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? coupon_start
		{
			get{ return _coupon_start; }
			set
			{
				this.OnPropertyValueChange(_.coupon_start,_coupon_start,value);
				this._coupon_start=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? coupon_end
		{
			get{ return _coupon_end; }
			set
			{
				this.OnPropertyValueChange(_.coupon_end,_coupon_end,value);
				this._coupon_end=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_link
		{
			get{ return _coupon_link; }
			set
			{
				this.OnPropertyValueChange(_.coupon_link,_coupon_link,value);
				this._coupon_link=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_secretword
		{
			get{ return _coupon_secretword; }
			set
			{
				this.OnPropertyValueChange(_.coupon_secretword,_coupon_secretword,value);
				this._coupon_secretword=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.product_id,
				_.product_name,
				_.main_picture,
				_.product_detail,
				_.shop_name,
				_.price,
				_.sales_amount,
				_.percent,
				_.salary,
				_.status,
				_.event_percent,
				_.event_salary,
				_.event_start,
				_.event_end,
				_.wangwang,
				_.taoke_short_url,
				_.taoke_url,
				_.taoke_secretword,
				_.coupon_amount,
				_.coupon_remaining,
				_.coupon_price,
				_.coupon_start,
				_.coupon_end,
				_.coupon_link,
				_.coupon_secretword};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._product_id,
				this._product_name,
				this._main_picture,
				this._product_detail,
				this._shop_name,
				this._price,
				this._sales_amount,
				this._percent,
				this._salary,
				this._status,
				this._event_percent,
				this._event_salary,
				this._event_start,
				this._event_end,
				this._wangwang,
				this._taoke_short_url,
				this._taoke_url,
				this._taoke_secretword,
				this._coupon_amount,
				this._coupon_remaining,
				this._coupon_price,
				this._coupon_start,
				this._coupon_end,
				this._coupon_link,
				this._coupon_secretword};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","high_products");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","high_products","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_id = new Field("product_id","high_products","product_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","high_products","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field main_picture = new Field("main_picture","high_products","main_picture");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_detail = new Field("product_detail","high_products","product_detail");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field shop_name = new Field("shop_name","high_products","shop_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","high_products","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sales_amount = new Field("sales_amount","high_products","sales_amount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field percent = new Field("percent","high_products","percent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field salary = new Field("salary","high_products","salary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status","high_products","status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field event_percent = new Field("event_percent","high_products","event_percent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field event_salary = new Field("event_salary","high_products","event_salary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field event_start = new Field("event_start","high_products","event_start");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field event_end = new Field("event_end","high_products","event_end");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wangwang = new Field("wangwang","high_products","wangwang");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field taoke_short_url = new Field("taoke_short_url","high_products","taoke_short_url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field taoke_url = new Field("taoke_url","high_products","taoke_url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field taoke_secretword = new Field("taoke_secretword","high_products","taoke_secretword");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_amount = new Field("coupon_amount","high_products","coupon_amount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_remaining = new Field("coupon_remaining","high_products","coupon_remaining");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_price = new Field("coupon_price","high_products","coupon_price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_start = new Field("coupon_start","high_products","coupon_start");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_end = new Field("coupon_end","high_products","coupon_end");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_link = new Field("coupon_link","high_products","coupon_link");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_secretword = new Field("coupon_secretword","high_products","coupon_secretword");
		}
		#endregion


	}
}

