//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model
{

	/// <summary>
	/// 实体类products 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("products")]
	[Serializable]
	public partial class products : Entity 
	{
		#region Model
		private long _id;
		private string _product_id;
		private string _product_name;
		private string _main_image;
		private string _detail_link_address;
		private string _first_level_category;
		private string _taoke_link;
		private string _price;
		private string _sales_amount;
		private string _percent;
		private string _salary;
		private string _wangwang;
		private string _saler_id;
		private string _shop_name;
		private string _platform_name;
		private string _coupon_id;
		private string _coupon_amount;
		private string _coupon_remaining;
		private string _coupon_money;
		private DateTime? _coupon_start;
		private DateTime? _coupon_end;
		private string _coupon_link;
		private string _coupon_taoke_link;
		/// <summary>
		/// 
		/// </summary>
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_id
		{
			get{ return _product_id; }
			set
			{
				this.OnPropertyValueChange(_.product_id,_product_id,value);
				this._product_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string main_image
		{
			get{ return _main_image; }
			set
			{
				this.OnPropertyValueChange(_.main_image,_main_image,value);
				this._main_image=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string detail_link_address
		{
			get{ return _detail_link_address; }
			set
			{
				this.OnPropertyValueChange(_.detail_link_address,_detail_link_address,value);
				this._detail_link_address=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string first_level_category
		{
			get{ return _first_level_category; }
			set
			{
				this.OnPropertyValueChange(_.first_level_category,_first_level_category,value);
				this._first_level_category=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string taoke_link
		{
			get{ return _taoke_link; }
			set
			{
				this.OnPropertyValueChange(_.taoke_link,_taoke_link,value);
				this._taoke_link=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sales_amount
		{
			get{ return _sales_amount; }
			set
			{
				this.OnPropertyValueChange(_.sales_amount,_sales_amount,value);
				this._sales_amount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string percent
		{
			get{ return _percent; }
			set
			{
				this.OnPropertyValueChange(_.percent,_percent,value);
				this._percent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string salary
		{
			get{ return _salary; }
			set
			{
				this.OnPropertyValueChange(_.salary,_salary,value);
				this._salary=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string wangwang
		{
			get{ return _wangwang; }
			set
			{
				this.OnPropertyValueChange(_.wangwang,_wangwang,value);
				this._wangwang=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string saler_id
		{
			get{ return _saler_id; }
			set
			{
				this.OnPropertyValueChange(_.saler_id,_saler_id,value);
				this._saler_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string shop_name
		{
			get{ return _shop_name; }
			set
			{
				this.OnPropertyValueChange(_.shop_name,_shop_name,value);
				this._shop_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string platform_name
		{
			get{ return _platform_name; }
			set
			{
				this.OnPropertyValueChange(_.platform_name,_platform_name,value);
				this._platform_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_id
		{
			get{ return _coupon_id; }
			set
			{
				this.OnPropertyValueChange(_.coupon_id,_coupon_id,value);
				this._coupon_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_amount
		{
			get{ return _coupon_amount; }
			set
			{
				this.OnPropertyValueChange(_.coupon_amount,_coupon_amount,value);
				this._coupon_amount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_remaining
		{
			get{ return _coupon_remaining; }
			set
			{
				this.OnPropertyValueChange(_.coupon_remaining,_coupon_remaining,value);
				this._coupon_remaining=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_money
		{
			get{ return _coupon_money; }
			set
			{
				this.OnPropertyValueChange(_.coupon_money,_coupon_money,value);
				this._coupon_money=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? coupon_start
		{
			get{ return _coupon_start; }
			set
			{
				this.OnPropertyValueChange(_.coupon_start,_coupon_start,value);
				this._coupon_start=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? coupon_end
		{
			get{ return _coupon_end; }
			set
			{
				this.OnPropertyValueChange(_.coupon_end,_coupon_end,value);
				this._coupon_end=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_link
		{
			get{ return _coupon_link; }
			set
			{
				this.OnPropertyValueChange(_.coupon_link,_coupon_link,value);
				this._coupon_link=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string coupon_taoke_link
		{
			get{ return _coupon_taoke_link; }
			set
			{
				this.OnPropertyValueChange(_.coupon_taoke_link,_coupon_taoke_link,value);
				this._coupon_taoke_link=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.product_id,
				_.product_name,
				_.main_image,
				_.detail_link_address,
				_.first_level_category,
				_.taoke_link,
				_.price,
				_.sales_amount,
				_.percent,
				_.salary,
				_.wangwang,
				_.saler_id,
				_.shop_name,
				_.platform_name,
				_.coupon_id,
				_.coupon_amount,
				_.coupon_remaining,
				_.coupon_money,
				_.coupon_start,
				_.coupon_end,
				_.coupon_link,
				_.coupon_taoke_link};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._product_id,
				this._product_name,
				this._main_image,
				this._detail_link_address,
				this._first_level_category,
				this._taoke_link,
				this._price,
				this._sales_amount,
				this._percent,
				this._salary,
				this._wangwang,
				this._saler_id,
				this._shop_name,
				this._platform_name,
				this._coupon_id,
				this._coupon_amount,
				this._coupon_remaining,
				this._coupon_money,
				this._coupon_start,
				this._coupon_end,
				this._coupon_link,
				this._coupon_taoke_link};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","products");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","products","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_id = new Field("product_id","products","product_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","products","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field main_image = new Field("main_image","products","main_image");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field detail_link_address = new Field("detail_link_address","products","detail_link_address");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field first_level_category = new Field("first_level_category","products","first_level_category");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field taoke_link = new Field("taoke_link","products","taoke_link");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","products","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sales_amount = new Field("sales_amount","products","sales_amount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field percent = new Field("percent","products","percent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field salary = new Field("salary","products","salary");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wangwang = new Field("wangwang","products","wangwang");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field saler_id = new Field("saler_id","products","saler_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field shop_name = new Field("shop_name","products","shop_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field platform_name = new Field("platform_name","products","platform_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_id = new Field("coupon_id","products","coupon_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_amount = new Field("coupon_amount","products","coupon_amount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_remaining = new Field("coupon_remaining","products","coupon_remaining");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_money = new Field("coupon_money","products","coupon_money");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_start = new Field("coupon_start","products","coupon_start");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_end = new Field("coupon_end","products","coupon_end");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_link = new Field("coupon_link","products","coupon_link");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field coupon_taoke_link = new Field("coupon_taoke_link","products","coupon_taoke_link");
		}
		#endregion


	}
}

