//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类common_status 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("common_status")]
	[Serializable]
	public partial class common_status : Entity 
	{
		#region Model
		private int _id;
		private string _table_name;
		private string _field_name;
		private string _status;
		private string _introduce;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string table_name
		{
			get{ return _table_name; }
			set
			{
				this.OnPropertyValueChange(_.table_name,_table_name,value);
				this._table_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string field_name
		{
			get{ return _field_name; }
			set
			{
				this.OnPropertyValueChange(_.field_name,_field_name,value);
				this._field_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string introduce
		{
			get{ return _introduce; }
			set
			{
				this.OnPropertyValueChange(_.introduce,_introduce,value);
				this._introduce=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.table_name,
				_.field_name,
				_.status,
				_.introduce};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._table_name,
				this._field_name,
				this._status,
				this._introduce};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","common_status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","common_status","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field table_name = new Field("table_name","common_status","table_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field field_name = new Field("field_name","common_status","field_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status","common_status","status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field introduce = new Field("introduce","common_status","introduce");
		}
		#endregion


	}
}

