//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类cp_province_deduct_log 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("cp_province_deduct_log")]
	[Serializable]
	public partial class cp_province_deduct_log : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _province_id;
		private int _sms_mo_deduct;
		private int _sms_mr_deduct;
		private int _mms_mo_deduct;
		private int _mms_mr_deduct;
		private string _operater;
		private DateTime? _modified_datetime;
		private string _acttype;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 合作方编号
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 省份编号
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 短信上行扣量
		/// </summary>
		public int sms_mo_deduct
		{
			get{ return _sms_mo_deduct; }
			set
			{
				this.OnPropertyValueChange(_.sms_mo_deduct,_sms_mo_deduct,value);
				this._sms_mo_deduct=value;
			}
		}
		/// <summary>
		/// 短信MR扣量
		/// </summary>
		public int sms_mr_deduct
		{
			get{ return _sms_mr_deduct; }
			set
			{
				this.OnPropertyValueChange(_.sms_mr_deduct,_sms_mr_deduct,value);
				this._sms_mr_deduct=value;
			}
		}
		/// <summary>
		/// 彩信上行扣量
		/// </summary>
		public int mms_mo_deduct
		{
			get{ return _mms_mo_deduct; }
			set
			{
				this.OnPropertyValueChange(_.mms_mo_deduct,_mms_mo_deduct,value);
				this._mms_mo_deduct=value;
			}
		}
		/// <summary>
		/// 彩信MR扣量
		/// </summary>
		public int mms_mr_deduct
		{
			get{ return _mms_mr_deduct; }
			set
			{
				this.OnPropertyValueChange(_.mms_mr_deduct,_mms_mr_deduct,value);
				this._mms_mr_deduct=value;
			}
		}
		/// <summary>
		/// 最近操作人
		/// </summary>
		public string operater
		{
			get{ return _operater; }
			set
			{
				this.OnPropertyValueChange(_.operater,_operater,value);
				this._operater=value;
			}
		}
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? modified_datetime
		{
			get{ return _modified_datetime; }
			set
			{
				this.OnPropertyValueChange(_.modified_datetime,_modified_datetime,value);
				this._modified_datetime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string acttype
		{
			get{ return _acttype; }
			set
			{
				this.OnPropertyValueChange(_.acttype,_acttype,value);
				this._acttype=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.province_id,
				_.sms_mo_deduct,
				_.sms_mr_deduct,
				_.mms_mo_deduct,
				_.mms_mr_deduct,
				_.operater,
				_.modified_datetime,
				_.acttype};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._province_id,
				this._sms_mo_deduct,
				this._sms_mr_deduct,
				this._mms_mo_deduct,
				this._mms_mr_deduct,
				this._operater,
				this._modified_datetime,
				this._acttype};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","cp_province_deduct_log");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","cp_province_deduct_log","id");
			/// <summary>
			/// 合作方编号
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","cp_province_deduct_log","合作方编号");
			/// <summary>
			/// 省份编号
			/// </summary>
			public readonly static Field province_id = new Field("province_id","cp_province_deduct_log","省份编号");
			/// <summary>
			/// 短信上行扣量
			/// </summary>
			public readonly static Field sms_mo_deduct = new Field("sms_mo_deduct","cp_province_deduct_log","短信上行扣量");
			/// <summary>
			/// 短信MR扣量
			/// </summary>
			public readonly static Field sms_mr_deduct = new Field("sms_mr_deduct","cp_province_deduct_log","短信MR扣量");
			/// <summary>
			/// 彩信上行扣量
			/// </summary>
			public readonly static Field mms_mo_deduct = new Field("mms_mo_deduct","cp_province_deduct_log","彩信上行扣量");
			/// <summary>
			/// 彩信MR扣量
			/// </summary>
			public readonly static Field mms_mr_deduct = new Field("mms_mr_deduct","cp_province_deduct_log","彩信MR扣量");
			/// <summary>
			/// 最近操作人
			/// </summary>
			public readonly static Field operater = new Field("operater","cp_province_deduct_log","最近操作人");
			/// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field modified_datetime = new Field("modified_datetime","cp_province_deduct_log","修改时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field acttype = new Field("acttype","cp_province_deduct_log","acttype");
		}
		#endregion


	}
}

