//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类daily_report_today 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("daily_report_today")]
	[Serializable]
	public partial class daily_report_today : Entity 
	{
		#region Model
		private int _id;
		private string _service_id;
		private string _cp_id;
		private string _sp_id;
		private string _ch_id;
		private string _province_id;
		private string _service_type;
		private bool? _order_type;
		private int _income;
		private decimal _cp_fc;
		private decimal _sp_fc;
		private int _mo_all_num;
		private int _mo_all_user_num;
		private int _mo_succ_num;
		private int _mo_succ_user_num;
		private int _mt_all_num;
		private int _mt_all_user_num;
		private int _mt_succ_num;
		private int _mt_succ_user_num;
		private DateTime? _count_date;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_id
		{
			get{ return _service_id; }
			set
			{
				this.OnPropertyValueChange(_.service_id,_service_id,value);
				this._service_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ch_id
		{
			get{ return _ch_id; }
			set
			{
				this.OnPropertyValueChange(_.ch_id,_ch_id,value);
				this._ch_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// _1 计次  9包月
		/// </summary>
		public bool? order_type
		{
			get{ return _order_type; }
			set
			{
				this.OnPropertyValueChange(_.order_type,_order_type,value);
				this._order_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int income
		{
			get{ return _income; }
			set
			{
				this.OnPropertyValueChange(_.income,_income,value);
				this._income=value;
			}
		}
		/// <summary>
		/// cp分成比例
		/// </summary>
		public decimal cp_fc
		{
			get{ return _cp_fc; }
			set
			{
				this.OnPropertyValueChange(_.cp_fc,_cp_fc,value);
				this._cp_fc=value;
			}
		}
		/// <summary>
		/// sp分成比例
		/// </summary>
		public decimal sp_fc
		{
			get{ return _sp_fc; }
			set
			{
				this.OnPropertyValueChange(_.sp_fc,_sp_fc,value);
				this._sp_fc=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mo_all_num
		{
			get{ return _mo_all_num; }
			set
			{
				this.OnPropertyValueChange(_.mo_all_num,_mo_all_num,value);
				this._mo_all_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mo_all_user_num
		{
			get{ return _mo_all_user_num; }
			set
			{
				this.OnPropertyValueChange(_.mo_all_user_num,_mo_all_user_num,value);
				this._mo_all_user_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mo_succ_num
		{
			get{ return _mo_succ_num; }
			set
			{
				this.OnPropertyValueChange(_.mo_succ_num,_mo_succ_num,value);
				this._mo_succ_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mo_succ_user_num
		{
			get{ return _mo_succ_user_num; }
			set
			{
				this.OnPropertyValueChange(_.mo_succ_user_num,_mo_succ_user_num,value);
				this._mo_succ_user_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mt_all_num
		{
			get{ return _mt_all_num; }
			set
			{
				this.OnPropertyValueChange(_.mt_all_num,_mt_all_num,value);
				this._mt_all_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mt_all_user_num
		{
			get{ return _mt_all_user_num; }
			set
			{
				this.OnPropertyValueChange(_.mt_all_user_num,_mt_all_user_num,value);
				this._mt_all_user_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mt_succ_num
		{
			get{ return _mt_succ_num; }
			set
			{
				this.OnPropertyValueChange(_.mt_succ_num,_mt_succ_num,value);
				this._mt_succ_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int mt_succ_user_num
		{
			get{ return _mt_succ_user_num; }
			set
			{
				this.OnPropertyValueChange(_.mt_succ_user_num,_mt_succ_user_num,value);
				this._mt_succ_user_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? count_date
		{
			get{ return _count_date; }
			set
			{
				this.OnPropertyValueChange(_.count_date,_count_date,value);
				this._count_date=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.service_id,
				_.cp_id,
				_.sp_id,
				_.ch_id,
				_.province_id,
				_.service_type,
				_.order_type,
				_.income,
				_.cp_fc,
				_.sp_fc,
				_.mo_all_num,
				_.mo_all_user_num,
				_.mo_succ_num,
				_.mo_succ_user_num,
				_.mt_all_num,
				_.mt_all_user_num,
				_.mt_succ_num,
				_.mt_succ_user_num,
				_.count_date};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._service_id,
				this._cp_id,
				this._sp_id,
				this._ch_id,
				this._province_id,
				this._service_type,
				this._order_type,
				this._income,
				this._cp_fc,
				this._sp_fc,
				this._mo_all_num,
				this._mo_all_user_num,
				this._mo_succ_num,
				this._mo_succ_user_num,
				this._mt_all_num,
				this._mt_all_user_num,
				this._mt_succ_num,
				this._mt_succ_user_num,
				this._count_date};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","daily_report_today");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","daily_report_today","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_id = new Field("service_id","daily_report_today","service_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","daily_report_today","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","daily_report_today","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ch_id = new Field("ch_id","daily_report_today","ch_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","daily_report_today","province_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_type = new Field("service_type","daily_report_today","service_type");
			/// <summary>
			/// _1 计次  9包月
			/// </summary>
			public readonly static Field order_type = new Field("order_type","daily_report_today","_1 计次  9包月");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field income = new Field("income","daily_report_today","income");
			/// <summary>
			/// cp分成比例
			/// </summary>
			public readonly static Field cp_fc = new Field("cp_fc","daily_report_today","cp分成比例");
			/// <summary>
			/// sp分成比例
			/// </summary>
			public readonly static Field sp_fc = new Field("sp_fc","daily_report_today","sp分成比例");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mo_all_num = new Field("mo_all_num","daily_report_today","mo_all_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mo_all_user_num = new Field("mo_all_user_num","daily_report_today","mo_all_user_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mo_succ_num = new Field("mo_succ_num","daily_report_today","mo_succ_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mo_succ_user_num = new Field("mo_succ_user_num","daily_report_today","mo_succ_user_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mt_all_num = new Field("mt_all_num","daily_report_today","mt_all_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mt_all_user_num = new Field("mt_all_user_num","daily_report_today","mt_all_user_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mt_succ_num = new Field("mt_succ_num","daily_report_today","mt_succ_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mt_succ_user_num = new Field("mt_succ_user_num","daily_report_today","mt_succ_user_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field count_date = new Field("count_date","daily_report_today","count_date");
		}
		#endregion


	}
}

