//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类h5_month_appinfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("h5_month_appinfo")]
	[Serializable]
	public partial class h5_month_appinfo : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _appname;
		private string _appkey;
		private string _sp_id;
		private string _price;
		private string _paycode;
		private string _sub_appname;
		private string _sdk_appid;
		private string _sdk_paycode;
		private string _td_paycode;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appname
		{
			get{ return _appname; }
			set
			{
				this.OnPropertyValueChange(_.appname,_appname,value);
				this._appname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appkey
		{
			get{ return _appkey; }
			set
			{
				this.OnPropertyValueChange(_.appkey,_appkey,value);
				this._appkey=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sub_appname
		{
			get{ return _sub_appname; }
			set
			{
				this.OnPropertyValueChange(_.sub_appname,_sub_appname,value);
				this._sub_appname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sdk_appid
		{
			get{ return _sdk_appid; }
			set
			{
				this.OnPropertyValueChange(_.sdk_appid,_sdk_appid,value);
				this._sdk_appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sdk_paycode
		{
			get{ return _sdk_paycode; }
			set
			{
				this.OnPropertyValueChange(_.sdk_paycode,_sdk_paycode,value);
				this._sdk_paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string td_paycode
		{
			get{ return _td_paycode; }
			set
			{
				this.OnPropertyValueChange(_.td_paycode,_td_paycode,value);
				this._td_paycode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.appname,
				_.appkey,
				_.sp_id,
				_.price,
				_.paycode,
				_.sub_appname,
				_.sdk_appid,
				_.sdk_paycode,
				_.td_paycode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._appname,
				this._appkey,
				this._sp_id,
				this._price,
				this._paycode,
				this._sub_appname,
				this._sdk_appid,
				this._sdk_paycode,
				this._td_paycode};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","h5_month_appinfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","h5_month_appinfo","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","h5_month_appinfo","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appname = new Field("appname","h5_month_appinfo","appname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appkey = new Field("appkey","h5_month_appinfo","appkey");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","h5_month_appinfo","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","h5_month_appinfo","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","h5_month_appinfo","paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sub_appname = new Field("sub_appname","h5_month_appinfo","sub_appname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sdk_appid = new Field("sdk_appid","h5_month_appinfo","sdk_appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sdk_paycode = new Field("sdk_paycode","h5_month_appinfo","sdk_paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field td_paycode = new Field("td_paycode","h5_month_appinfo","td_paycode");
		}
		#endregion


	}
}

