//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类icity_tf 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("icity_tf")]
	[Serializable]
	public partial class icity_tf : Entity 
	{
		#region Model
		private int _id;
		private string _tf_succ_ym;
		private string _cp_name;
		private string _mobile;
		private string _province_id;
		private string _trade_no;
		private string _app_name;
		private string _product_name;
		private string _ex_time;
		private string _price;
		private string _tf_price;
		private string _tf_succ_time;
		private string _type;
		private string _pic_url;
		private int? _del_stat;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tf_succ_ym
		{
			get{ return _tf_succ_ym; }
			set
			{
				this.OnPropertyValueChange(_.tf_succ_ym,_tf_succ_ym,value);
				this._tf_succ_ym=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_name
		{
			get{ return _cp_name; }
			set
			{
				this.OnPropertyValueChange(_.cp_name,_cp_name,value);
				this._cp_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string mobile
		{
			get{ return _mobile; }
			set
			{
				this.OnPropertyValueChange(_.mobile,_mobile,value);
				this._mobile=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string trade_no
		{
			get{ return _trade_no; }
			set
			{
				this.OnPropertyValueChange(_.trade_no,_trade_no,value);
				this._trade_no=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_name
		{
			get{ return _app_name; }
			set
			{
				this.OnPropertyValueChange(_.app_name,_app_name,value);
				this._app_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ex_time
		{
			get{ return _ex_time; }
			set
			{
				this.OnPropertyValueChange(_.ex_time,_ex_time,value);
				this._ex_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tf_price
		{
			get{ return _tf_price; }
			set
			{
				this.OnPropertyValueChange(_.tf_price,_tf_price,value);
				this._tf_price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tf_succ_time
		{
			get{ return _tf_succ_time; }
			set
			{
				this.OnPropertyValueChange(_.tf_succ_time,_tf_succ_time,value);
				this._tf_succ_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange(_.type,_type,value);
				this._type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string pic_url
		{
			get{ return _pic_url; }
			set
			{
				this.OnPropertyValueChange(_.pic_url,_pic_url,value);
				this._pic_url=value;
			}
		}
		/// <summary>
		/// _0正常 1已删除
		/// </summary>
		public int? del_stat
		{
			get{ return _del_stat; }
			set
			{
				this.OnPropertyValueChange(_.del_stat,_del_stat,value);
				this._del_stat=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.tf_succ_ym,
				_.cp_name,
				_.mobile,
				_.province_id,
				_.trade_no,
				_.app_name,
				_.product_name,
				_.ex_time,
				_.price,
				_.tf_price,
				_.tf_succ_time,
				_.type,
				_.pic_url,
				_.del_stat};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._tf_succ_ym,
				this._cp_name,
				this._mobile,
				this._province_id,
				this._trade_no,
				this._app_name,
				this._product_name,
				this._ex_time,
				this._price,
				this._tf_price,
				this._tf_succ_time,
				this._type,
				this._pic_url,
				this._del_stat};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","icity_tf");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","icity_tf","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tf_succ_ym = new Field("tf_succ_ym","icity_tf","tf_succ_ym");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_name = new Field("cp_name","icity_tf","cp_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field mobile = new Field("mobile","icity_tf","mobile");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","icity_tf","province_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field trade_no = new Field("trade_no","icity_tf","trade_no");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_name = new Field("app_name","icity_tf","app_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","icity_tf","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ex_time = new Field("ex_time","icity_tf","ex_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","icity_tf","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tf_price = new Field("tf_price","icity_tf","tf_price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tf_succ_time = new Field("tf_succ_time","icity_tf","tf_succ_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type","icity_tf","type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pic_url = new Field("pic_url","icity_tf","pic_url");
			/// <summary>
			/// _0正常 1已删除
			/// </summary>
			public readonly static Field del_stat = new Field("del_stat","icity_tf","_0正常 1已删除");
		}
		#endregion


	}
}

