//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类limit_auto 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("limit_auto")]
	[Serializable]
	public partial class limit_auto : Entity 
	{
		#region Model
		private int _id;
		private string _sp_id;
		private string _cp_id;
		private string _service_type;
		private int? _opentime;
		private int? _closetime;
		private string _auto_date;
		private int? _closeprice;
		private int? _opentimestat;
		private int? _closetimestat;
		private int? _pricestat;
		private string _add_user;
		private DateTime? _add_time;
		private string _province_id;
		private int? _closenum;
		private int? _numstat;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? opentime
		{
			get{ return _opentime; }
			set
			{
				this.OnPropertyValueChange(_.opentime,_opentime,value);
				this._opentime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? closetime
		{
			get{ return _closetime; }
			set
			{
				this.OnPropertyValueChange(_.closetime,_closetime,value);
				this._closetime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string auto_date
		{
			get{ return _auto_date; }
			set
			{
				this.OnPropertyValueChange(_.auto_date,_auto_date,value);
				this._auto_date=value;
			}
		}
		/// <summary>
		/// 元单位
		/// </summary>
		public int? closeprice
		{
			get{ return _closeprice; }
			set
			{
				this.OnPropertyValueChange(_.closeprice,_closeprice,value);
				this._closeprice=value;
			}
		}
		/// <summary>
		/// _0未执行过 1已执行过不在操作
		/// </summary>
		public int? opentimestat
		{
			get{ return _opentimestat; }
			set
			{
				this.OnPropertyValueChange(_.opentimestat,_opentimestat,value);
				this._opentimestat=value;
			}
		}
		/// <summary>
		/// _0未执行过 1已执行过不在操作
		/// </summary>
		public int? closetimestat
		{
			get{ return _closetimestat; }
			set
			{
				this.OnPropertyValueChange(_.closetimestat,_closetimestat,value);
				this._closetimestat=value;
			}
		}
		/// <summary>
		/// _0未执行过 1已执行过不在操作
		/// </summary>
		public int? pricestat
		{
			get{ return _pricestat; }
			set
			{
				this.OnPropertyValueChange(_.pricestat,_pricestat,value);
				this._pricestat=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string add_user
		{
			get{ return _add_user; }
			set
			{
				this.OnPropertyValueChange(_.add_user,_add_user,value);
				this._add_user=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 到量关闭条数
		/// </summary>
		public int? closenum
		{
			get{ return _closenum; }
			set
			{
				this.OnPropertyValueChange(_.closenum,_closenum,value);
				this._closenum=value;
			}
		}
		/// <summary>
		/// _0未执行过 1已执行过不在操作
		/// </summary>
		public int? numstat
		{
			get{ return _numstat; }
			set
			{
				this.OnPropertyValueChange(_.numstat,_numstat,value);
				this._numstat=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.sp_id,
				_.cp_id,
				_.service_type,
				_.opentime,
				_.closetime,
				_.auto_date,
				_.closeprice,
				_.opentimestat,
				_.closetimestat,
				_.pricestat,
				_.add_user,
				_.add_time,
				_.province_id,
				_.closenum,
				_.numstat};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._sp_id,
				this._cp_id,
				this._service_type,
				this._opentime,
				this._closetime,
				this._auto_date,
				this._closeprice,
				this._opentimestat,
				this._closetimestat,
				this._pricestat,
				this._add_user,
				this._add_time,
				this._province_id,
				this._closenum,
				this._numstat};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","limit_auto");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","limit_auto","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","limit_auto","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","limit_auto","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_type = new Field("service_type","limit_auto","service_type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field opentime = new Field("opentime","limit_auto","opentime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field closetime = new Field("closetime","limit_auto","closetime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field auto_date = new Field("auto_date","limit_auto","auto_date");
			/// <summary>
			/// 元单位
			/// </summary>
			public readonly static Field closeprice = new Field("closeprice","limit_auto","元单位");
			/// <summary>
			/// _0未执行过 1已执行过不在操作
			/// </summary>
			public readonly static Field opentimestat = new Field("opentimestat","limit_auto","_0未执行过 1已执行过不在操作");
			/// <summary>
			/// _0未执行过 1已执行过不在操作
			/// </summary>
			public readonly static Field closetimestat = new Field("closetimestat","limit_auto","_0未执行过 1已执行过不在操作");
			/// <summary>
			/// _0未执行过 1已执行过不在操作
			/// </summary>
			public readonly static Field pricestat = new Field("pricestat","limit_auto","_0未执行过 1已执行过不在操作");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_user = new Field("add_user","limit_auto","add_user");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_time = new Field("add_time","limit_auto","add_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","limit_auto","province_id");
			/// <summary>
			/// 到量关闭条数
			/// </summary>
			public readonly static Field closenum = new Field("closenum","limit_auto","到量关闭条数");
			/// <summary>
			/// _0未执行过 1已执行过不在操作
			/// </summary>
			public readonly static Field numstat = new Field("numstat","limit_auto","_0未执行过 1已执行过不在操作");
		}
		#endregion


	}
}

