//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类new_type_cp 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("new_type_cp")]
	[Serializable]
	public partial class new_type_cp : Entity 
	{
		#region Model
		private int _id;
		private string _cp_id;
		private string _url;
		private string _sp_id;
		private string _service_type;
		private DateTime? _datetime;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string url
		{
			get{ return _url; }
			set
			{
				this.OnPropertyValueChange(_.url,_url,value);
				this._url=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? datetime
		{
			get{ return _datetime; }
			set
			{
				this.OnPropertyValueChange(_.datetime,_datetime,value);
				this._datetime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.cp_id,
				_.url,
				_.sp_id,
				_.service_type,
				_.datetime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._cp_id,
				this._url,
				this._sp_id,
				this._service_type,
				this._datetime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","new_type_cp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","new_type_cp","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","new_type_cp","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field url = new Field("url","new_type_cp","url");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","new_type_cp","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_type = new Field("service_type","new_type_cp","service_type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field datetime = new Field("datetime","new_type_cp","datetime");
		}
		#endregion


	}
}

