//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类service_info_comic_fee 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("service_info_comic_fee")]
	[Serializable]
	public partial class service_info_comic_fee : Entity 
	{
		#region Model
		private int _id;
		private string _app_name;
		private string _service_id;
		private string _service_name;
		private string _fee_num;
		private string _content;
		private string _sms_content;
		private string _ch_id;
		private string _cp_id;
		private string _sp_id;
		private string _service_type;
		private int? _price;
		private DateTime? _coop_date;
		private int _coop_status;
		private int? _match_type;
		private string _channel_id;
		private DateTime? _add_time;
		private DateTime? _pass_time;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 应用名称
		/// </summary>
		public string app_name
		{
			get{ return _app_name; }
			set
			{
				this.OnPropertyValueChange(_.app_name,_app_name,value);
				this._app_name=value;
			}
		}
		/// <summary>
		/// 业务id/道具id
		/// </summary>
		public string service_id
		{
			get{ return _service_id; }
			set
			{
				this.OnPropertyValueChange(_.service_id,_service_id,value);
				this._service_id=value;
			}
		}
		/// <summary>
		/// 道具名称
		/// </summary>
		public string service_name
		{
			get{ return _service_name; }
			set
			{
				this.OnPropertyValueChange(_.service_name,_service_name,value);
				this._service_name=value;
			}
		}
		/// <summary>
		/// 计费道具编号
		/// </summary>
		public string fee_num
		{
			get{ return _fee_num; }
			set
			{
				this.OnPropertyValueChange(_.fee_num,_fee_num,value);
				this._fee_num=value;
			}
		}
		/// <summary>
		/// 短、彩指令
		/// </summary>
		public string content
		{
			get{ return _content; }
			set
			{
				this.OnPropertyValueChange(_.content,_content,value);
				this._content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sms_content
		{
			get{ return _sms_content; }
			set
			{
				this.OnPropertyValueChange(_.sms_content,_sms_content,value);
				this._sms_content=value;
			}
		}
		/// <summary>
		/// 游戏id,长号码
		/// </summary>
		public string ch_id
		{
			get{ return _ch_id; }
			set
			{
				this.OnPropertyValueChange(_.ch_id,_ch_id,value);
				this._ch_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 业务线类型
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 资费
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 合作时间
		/// </summary>
		public DateTime? coop_date
		{
			get{ return _coop_date; }
			set
			{
				this.OnPropertyValueChange(_.coop_date,_coop_date,value);
				this._coop_date=value;
			}
		}
		/// <summary>
		/// _0 开通 1关闭
		/// </summary>
		public int coop_status
		{
			get{ return _coop_status; }
			set
			{
				this.OnPropertyValueChange(_.coop_status,_coop_status,value);
				this._coop_status=value;
			}
		}
		/// <summary>
		/// _0模糊匹配  1精确匹配（短彩匹配类型）
		/// </summary>
		public int? match_type
		{
			get{ return _match_type; }
			set
			{
				this.OnPropertyValueChange(_.match_type,_match_type,value);
				this._match_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string channel_id
		{
			get{ return _channel_id; }
			set
			{
				this.OnPropertyValueChange(_.channel_id,_channel_id,value);
				this._channel_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? add_time
		{
			get{ return _add_time; }
			set
			{
				this.OnPropertyValueChange(_.add_time,_add_time,value);
				this._add_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? pass_time
		{
			get{ return _pass_time; }
			set
			{
				this.OnPropertyValueChange(_.pass_time,_pass_time,value);
				this._pass_time=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.app_name,
				_.service_id,
				_.service_name,
				_.fee_num,
				_.content,
				_.sms_content,
				_.ch_id,
				_.cp_id,
				_.sp_id,
				_.service_type,
				_.price,
				_.coop_date,
				_.coop_status,
				_.match_type,
				_.channel_id,
				_.add_time,
				_.pass_time};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._app_name,
				this._service_id,
				this._service_name,
				this._fee_num,
				this._content,
				this._sms_content,
				this._ch_id,
				this._cp_id,
				this._sp_id,
				this._service_type,
				this._price,
				this._coop_date,
				this._coop_status,
				this._match_type,
				this._channel_id,
				this._add_time,
				this._pass_time};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","service_info_comic_fee");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","service_info_comic_fee","id");
			/// <summary>
			/// 应用名称
			/// </summary>
			public readonly static Field app_name = new Field("app_name","service_info_comic_fee","应用名称");
			/// <summary>
			/// 业务id/道具id
			/// </summary>
			public readonly static Field service_id = new Field("service_id","service_info_comic_fee","业务id/道具id");
			/// <summary>
			/// 道具名称
			/// </summary>
			public readonly static Field service_name = new Field("service_name","service_info_comic_fee","道具名称");
			/// <summary>
			/// 计费道具编号
			/// </summary>
			public readonly static Field fee_num = new Field("fee_num","service_info_comic_fee","计费道具编号");
			/// <summary>
			/// 短、彩指令
			/// </summary>
			public readonly static Field content = new Field("content","service_info_comic_fee","短、彩指令");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sms_content = new Field("sms_content","service_info_comic_fee","sms_content");
			/// <summary>
			/// 游戏id,长号码
			/// </summary>
			public readonly static Field ch_id = new Field("ch_id","service_info_comic_fee","游戏id,长号码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","service_info_comic_fee","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","service_info_comic_fee","sp_id");
			/// <summary>
			/// 业务线类型
			/// </summary>
			public readonly static Field service_type = new Field("service_type","service_info_comic_fee","业务线类型");
			/// <summary>
			/// 资费
			/// </summary>
			public readonly static Field price = new Field("price","service_info_comic_fee","资费");
			/// <summary>
			/// 合作时间
			/// </summary>
			public readonly static Field coop_date = new Field("coop_date","service_info_comic_fee","合作时间");
			/// <summary>
			/// _0 开通 1关闭
			/// </summary>
			public readonly static Field coop_status = new Field("coop_status","service_info_comic_fee","_0 开通 1关闭");
			/// <summary>
			/// _0模糊匹配  1精确匹配（短彩匹配类型）
			/// </summary>
			public readonly static Field match_type = new Field("match_type","service_info_comic_fee","_0模糊匹配  1精确匹配（短彩匹配类型）");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field channel_id = new Field("channel_id","service_info_comic_fee","channel_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field add_time = new Field("add_time","service_info_comic_fee","add_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pass_time = new Field("pass_time","service_info_comic_fee","pass_time");
		}
		#endregion


	}
}

