//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类tb_admin_class 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("tb_admin_class")]
	[Serializable]
	public partial class tb_admin_class : Entity 
	{
		#region Model
		private int _classid;
		private string _classname;
		private short? _classpid;
		private string _classurl;
		private bool _status;
		private int _orders;
		private int _font;
		private int _target;
		/// <summary>
		/// 
		/// </summary>
		public int classid
		{
			get{ return _classid; }
			set
			{
				this.OnPropertyValueChange(_.classid,_classid,value);
				this._classid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string classname
		{
			get{ return _classname; }
			set
			{
				this.OnPropertyValueChange(_.classname,_classname,value);
				this._classname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public short? classpid
		{
			get{ return _classpid; }
			set
			{
				this.OnPropertyValueChange(_.classpid,_classpid,value);
				this._classpid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string classurl
		{
			get{ return _classurl; }
			set
			{
				this.OnPropertyValueChange(_.classurl,_classurl,value);
				this._classurl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int orders
		{
			get{ return _orders; }
			set
			{
				this.OnPropertyValueChange(_.orders,_orders,value);
				this._orders=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int font
		{
			get{ return _font; }
			set
			{
				this.OnPropertyValueChange(_.font,_font,value);
				this._font=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int target
		{
			get{ return _target; }
			set
			{
				this.OnPropertyValueChange(_.target,_target,value);
				this._target=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.classid};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.classid,
				_.classname,
				_.classpid,
				_.classurl,
				_.status,
				_.orders,
				_.font,
				_.target};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._classid,
				this._classname,
				this._classpid,
				this._classurl,
				this._status,
				this._orders,
				this._font,
				this._target};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","tb_admin_class");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field classid = new Field("classid","tb_admin_class","classid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field classname = new Field("classname","tb_admin_class","classname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field classpid = new Field("classpid","tb_admin_class","classpid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field classurl = new Field("classurl","tb_admin_class","classurl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status","tb_admin_class","status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field orders = new Field("orders","tb_admin_class","orders");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field font = new Field("font","tb_admin_class","font");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target = new Field("target","tb_admin_class","target");
		}
		#endregion


	}
}

