//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类tb_loginlog 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("tb_loginlog")]
	[Serializable]
	public partial class tb_loginlog : Entity 
	{
		#region Model
		private int _id;
		private string _username;
		private DateTime _logintime;
		private string _ip;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string username
		{
			get{ return _username; }
			set
			{
				this.OnPropertyValueChange(_.username,_username,value);
				this._username=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime logintime
		{
			get{ return _logintime; }
			set
			{
				this.OnPropertyValueChange(_.logintime,_logintime,value);
				this._logintime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ip
		{
			get{ return _ip; }
			set
			{
				this.OnPropertyValueChange(_.ip,_ip,value);
				this._ip=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.username,
				_.logintime,
				_.ip};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._username,
				this._logintime,
				this._ip};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","tb_loginlog");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","tb_loginlog","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field username = new Field("username","tb_loginlog","username");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field logintime = new Field("logintime","tb_loginlog","logintime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ip = new Field("ip","tb_loginlog","ip");
		}
		#endregion


	}
}

