//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类ts_cpn_info 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("ts_cpn_info")]
	[Serializable]
	public partial class ts_cpn_info : Entity 
	{
		#region Model
		private int _id;
		private int? _pid;
		private DateTime? _sl_date;
		private string _cpn;
		private string _province;
		private DateTime? _dg_date;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? pid
		{
			get{ return _pid; }
			set
			{
				this.OnPropertyValueChange(_.pid,_pid,value);
				this._pid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? sl_date
		{
			get{ return _sl_date; }
			set
			{
				this.OnPropertyValueChange(_.sl_date,_sl_date,value);
				this._sl_date=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cpn
		{
			get{ return _cpn; }
			set
			{
				this.OnPropertyValueChange(_.cpn,_cpn,value);
				this._cpn=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province
		{
			get{ return _province; }
			set
			{
				this.OnPropertyValueChange(_.province,_province,value);
				this._province=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? dg_date
		{
			get{ return _dg_date; }
			set
			{
				this.OnPropertyValueChange(_.dg_date,_dg_date,value);
				this._dg_date=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.pid,
				_.sl_date,
				_.cpn,
				_.province,
				_.dg_date};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._pid,
				this._sl_date,
				this._cpn,
				this._province,
				this._dg_date};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ts_cpn_info");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","ts_cpn_info","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pid = new Field("pid","ts_cpn_info","pid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sl_date = new Field("sl_date","ts_cpn_info","sl_date");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cpn = new Field("cpn","ts_cpn_info","cpn");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province = new Field("province","ts_cpn_info","province");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dg_date = new Field("dg_date","ts_cpn_info","dg_date");
		}
		#endregion


	}
}

