//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类vc_sms_charge_mo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vc_sms_charge_mo")]
	[Serializable]
	public partial class vc_sms_charge_mo : Entity 
	{
		#region Model
		private long _id;
		private string _sign;
		private string _phone;
		private string _ordersn;
		private string _smscontent;
		private string _chargeno;
		private DateTime? _createtime;
		private DateTime? _timestamp;
		private DateTime? _ex_time;
		private string _status;
		private string _province_id;
		private string _area_code;
		private string _product_id;
		private string _app_name;
		private string _product_name;
		private int? _price;
		private string _fee_num;
		private string _cp_id;
		private string _sp_id;
		private string _service_type;
		/// <summary>
		/// 
		/// </summary>
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sign
		{
			get{ return _sign; }
			set
			{
				this.OnPropertyValueChange(_.sign,_sign,value);
				this._sign=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange(_.phone,_phone,value);
				this._phone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ordersn
		{
			get{ return _ordersn; }
			set
			{
				this.OnPropertyValueChange(_.ordersn,_ordersn,value);
				this._ordersn=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string smscontent
		{
			get{ return _smscontent; }
			set
			{
				this.OnPropertyValueChange(_.smscontent,_smscontent,value);
				this._smscontent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string chargeno
		{
			get{ return _chargeno; }
			set
			{
				this.OnPropertyValueChange(_.chargeno,_chargeno,value);
				this._chargeno=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? createtime
		{
			get{ return _createtime; }
			set
			{
				this.OnPropertyValueChange(_.createtime,_createtime,value);
				this._createtime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? timestamp
		{
			get{ return _timestamp; }
			set
			{
				this.OnPropertyValueChange(_.timestamp,_timestamp,value);
				this._timestamp=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ex_time
		{
			get{ return _ex_time; }
			set
			{
				this.OnPropertyValueChange(_.ex_time,_ex_time,value);
				this._ex_time=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange(_.status,_status,value);
				this._status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string province_id
		{
			get{ return _province_id; }
			set
			{
				this.OnPropertyValueChange(_.province_id,_province_id,value);
				this._province_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string area_code
		{
			get{ return _area_code; }
			set
			{
				this.OnPropertyValueChange(_.area_code,_area_code,value);
				this._area_code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_id
		{
			get{ return _product_id; }
			set
			{
				this.OnPropertyValueChange(_.product_id,_product_id,value);
				this._product_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string app_name
		{
			get{ return _app_name; }
			set
			{
				this.OnPropertyValueChange(_.app_name,_app_name,value);
				this._app_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string fee_num
		{
			get{ return _fee_num; }
			set
			{
				this.OnPropertyValueChange(_.fee_num,_fee_num,value);
				this._fee_num=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string cp_id
		{
			get{ return _cp_id; }
			set
			{
				this.OnPropertyValueChange(_.cp_id,_cp_id,value);
				this._cp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.sign,
				_.phone,
				_.ordersn,
				_.smscontent,
				_.chargeno,
				_.createtime,
				_.timestamp,
				_.ex_time,
				_.status,
				_.province_id,
				_.area_code,
				_.product_id,
				_.app_name,
				_.product_name,
				_.price,
				_.fee_num,
				_.cp_id,
				_.sp_id,
				_.service_type};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._sign,
				this._phone,
				this._ordersn,
				this._smscontent,
				this._chargeno,
				this._createtime,
				this._timestamp,
				this._ex_time,
				this._status,
				this._province_id,
				this._area_code,
				this._product_id,
				this._app_name,
				this._product_name,
				this._price,
				this._fee_num,
				this._cp_id,
				this._sp_id,
				this._service_type};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vc_sms_charge_mo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","vc_sms_charge_mo","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sign = new Field("sign","vc_sms_charge_mo","sign");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone","vc_sms_charge_mo","phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ordersn = new Field("ordersn","vc_sms_charge_mo","ordersn");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field smscontent = new Field("smscontent","vc_sms_charge_mo","smscontent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field chargeno = new Field("chargeno","vc_sms_charge_mo","chargeno");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field createtime = new Field("createtime","vc_sms_charge_mo","createtime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field timestamp = new Field("timestamp","vc_sms_charge_mo","timestamp");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ex_time = new Field("ex_time","vc_sms_charge_mo","ex_time");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status","vc_sms_charge_mo","status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field province_id = new Field("province_id","vc_sms_charge_mo","province_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field area_code = new Field("area_code","vc_sms_charge_mo","area_code");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_id = new Field("product_id","vc_sms_charge_mo","product_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field app_name = new Field("app_name","vc_sms_charge_mo","app_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","vc_sms_charge_mo","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","vc_sms_charge_mo","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field fee_num = new Field("fee_num","vc_sms_charge_mo","fee_num");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field cp_id = new Field("cp_id","vc_sms_charge_mo","cp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","vc_sms_charge_mo","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field service_type = new Field("service_type","vc_sms_charge_mo","service_type");
		}
		#endregion


	}
}

