//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace NQuick.Model.DmComicPlatform
{

	/// <summary>
	/// 实体类vc_sdk_appinfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vc_sdk_appinfo")]
	[Serializable]
	public partial class vc_sdk_appinfo : Entity 
	{
		#region Model
		private int _id;
		private string _appid;
		private string _product_name;
		private string _paycode;
		private string _sp_id;
		private string _price;
		private string _service_type;
		private string _appname;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appid
		{
			get{ return _appid; }
			set
			{
				this.OnPropertyValueChange(_.appid,_appid,value);
				this._appid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string product_name
		{
			get{ return _product_name; }
			set
			{
				this.OnPropertyValueChange(_.product_name,_product_name,value);
				this._product_name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string paycode
		{
			get{ return _paycode; }
			set
			{
				this.OnPropertyValueChange(_.paycode,_paycode,value);
				this._paycode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string sp_id
		{
			get{ return _sp_id; }
			set
			{
				this.OnPropertyValueChange(_.sp_id,_sp_id,value);
				this._sp_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string price
		{
			get{ return _price; }
			set
			{
				this.OnPropertyValueChange(_.price,_price,value);
				this._price=value;
			}
		}
		/// <summary>
		/// _1点播  2包月
		/// </summary>
		public string service_type
		{
			get{ return _service_type; }
			set
			{
				this.OnPropertyValueChange(_.service_type,_service_type,value);
				this._service_type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string appname
		{
			get{ return _appname; }
			set
			{
				this.OnPropertyValueChange(_.appname,_appname,value);
				this._appname=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.appid,
				_.product_name,
				_.paycode,
				_.sp_id,
				_.price,
				_.service_type,
				_.appname};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._appid,
				this._product_name,
				this._paycode,
				this._sp_id,
				this._price,
				this._service_type,
				this._appname};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vc_sdk_appinfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","vc_sdk_appinfo","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appid = new Field("appid","vc_sdk_appinfo","appid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field product_name = new Field("product_name","vc_sdk_appinfo","product_name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field paycode = new Field("paycode","vc_sdk_appinfo","paycode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sp_id = new Field("sp_id","vc_sdk_appinfo","sp_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field price = new Field("price","vc_sdk_appinfo","price");
			/// <summary>
			/// _1点播  2包月
			/// </summary>
			public readonly static Field service_type = new Field("service_type","vc_sdk_appinfo","_1点播  2包月");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field appname = new Field("appname","vc_sdk_appinfo","appname");
		}
		#endregion


	}
}

